package facade.amazonaws.services.cloudhsmv2

import scalajs._

type BackupPolicy = "DEFAULT"
object BackupPolicy {
  val DEFAULT: "DEFAULT" = "DEFAULT"

  @inline def values = js.Array[BackupPolicy](DEFAULT)
}

type BackupRetentionType = "DAYS"
object BackupRetentionType {
  val DAYS: "DAYS" = "DAYS"

  @inline def values = js.Array[BackupRetentionType](DAYS)
}

type BackupState = "CREATE_IN_PROGRESS" | "READY" | "DELETED" | "PENDING_DELETION"
object BackupState {
  val CREATE_IN_PROGRESS: "CREATE_IN_PROGRESS" = "CREATE_IN_PROGRESS"
  val READY: "READY" = "READY"
  val DELETED: "DELETED" = "DELETED"
  val PENDING_DELETION: "PENDING_DELETION" = "PENDING_DELETION"

  @inline def values = js.Array[BackupState](CREATE_IN_PROGRESS, READY, DELETED, PENDING_DELETION)
}

type ClusterState = "CREATE_IN_PROGRESS" | "UNINITIALIZED" | "INITIALIZE_IN_PROGRESS" | "INITIALIZED" | "ACTIVE" | "UPDATE_IN_PROGRESS" | "DELETE_IN_PROGRESS" | "DELETED" | "DEGRADED"
object ClusterState {
  val CREATE_IN_PROGRESS: "CREATE_IN_PROGRESS" = "CREATE_IN_PROGRESS"
  val UNINITIALIZED: "UNINITIALIZED" = "UNINITIALIZED"
  val INITIALIZE_IN_PROGRESS: "INITIALIZE_IN_PROGRESS" = "INITIALIZE_IN_PROGRESS"
  val INITIALIZED: "INITIALIZED" = "INITIALIZED"
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val UPDATE_IN_PROGRESS: "UPDATE_IN_PROGRESS" = "UPDATE_IN_PROGRESS"
  val DELETE_IN_PROGRESS: "DELETE_IN_PROGRESS" = "DELETE_IN_PROGRESS"
  val DELETED: "DELETED" = "DELETED"
  val DEGRADED: "DEGRADED" = "DEGRADED"

  @inline def values = js.Array[ClusterState](CREATE_IN_PROGRESS, UNINITIALIZED, INITIALIZE_IN_PROGRESS, INITIALIZED, ACTIVE, UPDATE_IN_PROGRESS, DELETE_IN_PROGRESS, DELETED, DEGRADED)
}

type HsmState = "CREATE_IN_PROGRESS" | "ACTIVE" | "DEGRADED" | "DELETE_IN_PROGRESS" | "DELETED"
object HsmState {
  val CREATE_IN_PROGRESS: "CREATE_IN_PROGRESS" = "CREATE_IN_PROGRESS"
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val DEGRADED: "DEGRADED" = "DEGRADED"
  val DELETE_IN_PROGRESS: "DELETE_IN_PROGRESS" = "DELETE_IN_PROGRESS"
  val DELETED: "DELETED" = "DELETED"

  @inline def values = js.Array[HsmState](CREATE_IN_PROGRESS, ACTIVE, DEGRADED, DELETE_IN_PROGRESS, DELETED)
}
