package facade.amazonaws.services.devicefarm

import scalajs.js

type ArtifactCategory = "SCREENSHOT" | "FILE" | "LOG"
object ArtifactCategory {
  inline val SCREENSHOT: "SCREENSHOT" = "SCREENSHOT"
  inline val FILE: "FILE" = "FILE"
  inline val LOG: "LOG" = "LOG"

  inline def values: js.Array[ArtifactCategory] = js.Array(SCREENSHOT, FILE, LOG)
}

type ArtifactType = "UNKNOWN" | "SCREENSHOT" | "DEVICE_LOG" | "MESSAGE_LOG" | "VIDEO_LOG" | "RESULT_LOG" | "SERVICE_LOG" | "WEBKIT_LOG" | "INSTRUMENTATION_OUTPUT" | "EXERCISER_MONKEY_OUTPUT" | "CALABASH_JSON_OUTPUT" | "CALABASH_PRETTY_OUTPUT" | "CALABASH_STANDARD_OUTPUT" | "CALABASH_JAVA_XML_OUTPUT" | "AUTOMATION_OUTPUT" | "APPIUM_SERVER_OUTPUT" | "APPIUM_JAVA_OUTPUT" | "APPIUM_JAVA_XML_OUTPUT" | "APPIUM_PYTHON_OUTPUT" | "APPIUM_PYTHON_XML_OUTPUT" | "EXPLORER_EVENT_LOG" | "EXPLORER_SUMMARY_LOG" | "APPLICATION_CRASH_REPORT" | "XCTEST_LOG" | "VIDEO" | "CUSTOMER_ARTIFACT" | "CUSTOMER_ARTIFACT_LOG" | "TESTSPEC_OUTPUT"
object ArtifactType {
  inline val UNKNOWN: "UNKNOWN" = "UNKNOWN"
  inline val SCREENSHOT: "SCREENSHOT" = "SCREENSHOT"
  inline val DEVICE_LOG: "DEVICE_LOG" = "DEVICE_LOG"
  inline val MESSAGE_LOG: "MESSAGE_LOG" = "MESSAGE_LOG"
  inline val VIDEO_LOG: "VIDEO_LOG" = "VIDEO_LOG"
  inline val RESULT_LOG: "RESULT_LOG" = "RESULT_LOG"
  inline val SERVICE_LOG: "SERVICE_LOG" = "SERVICE_LOG"
  inline val WEBKIT_LOG: "WEBKIT_LOG" = "WEBKIT_LOG"
  inline val INSTRUMENTATION_OUTPUT: "INSTRUMENTATION_OUTPUT" = "INSTRUMENTATION_OUTPUT"
  inline val EXERCISER_MONKEY_OUTPUT: "EXERCISER_MONKEY_OUTPUT" = "EXERCISER_MONKEY_OUTPUT"
  inline val CALABASH_JSON_OUTPUT: "CALABASH_JSON_OUTPUT" = "CALABASH_JSON_OUTPUT"
  inline val CALABASH_PRETTY_OUTPUT: "CALABASH_PRETTY_OUTPUT" = "CALABASH_PRETTY_OUTPUT"
  inline val CALABASH_STANDARD_OUTPUT: "CALABASH_STANDARD_OUTPUT" = "CALABASH_STANDARD_OUTPUT"
  inline val CALABASH_JAVA_XML_OUTPUT: "CALABASH_JAVA_XML_OUTPUT" = "CALABASH_JAVA_XML_OUTPUT"
  inline val AUTOMATION_OUTPUT: "AUTOMATION_OUTPUT" = "AUTOMATION_OUTPUT"
  inline val APPIUM_SERVER_OUTPUT: "APPIUM_SERVER_OUTPUT" = "APPIUM_SERVER_OUTPUT"
  inline val APPIUM_JAVA_OUTPUT: "APPIUM_JAVA_OUTPUT" = "APPIUM_JAVA_OUTPUT"
  inline val APPIUM_JAVA_XML_OUTPUT: "APPIUM_JAVA_XML_OUTPUT" = "APPIUM_JAVA_XML_OUTPUT"
  inline val APPIUM_PYTHON_OUTPUT: "APPIUM_PYTHON_OUTPUT" = "APPIUM_PYTHON_OUTPUT"
  inline val APPIUM_PYTHON_XML_OUTPUT: "APPIUM_PYTHON_XML_OUTPUT" = "APPIUM_PYTHON_XML_OUTPUT"
  inline val EXPLORER_EVENT_LOG: "EXPLORER_EVENT_LOG" = "EXPLORER_EVENT_LOG"
  inline val EXPLORER_SUMMARY_LOG: "EXPLORER_SUMMARY_LOG" = "EXPLORER_SUMMARY_LOG"
  inline val APPLICATION_CRASH_REPORT: "APPLICATION_CRASH_REPORT" = "APPLICATION_CRASH_REPORT"
  inline val XCTEST_LOG: "XCTEST_LOG" = "XCTEST_LOG"
  inline val VIDEO: "VIDEO" = "VIDEO"
  inline val CUSTOMER_ARTIFACT: "CUSTOMER_ARTIFACT" = "CUSTOMER_ARTIFACT"
  inline val CUSTOMER_ARTIFACT_LOG: "CUSTOMER_ARTIFACT_LOG" = "CUSTOMER_ARTIFACT_LOG"
  inline val TESTSPEC_OUTPUT: "TESTSPEC_OUTPUT" = "TESTSPEC_OUTPUT"

  inline def values: js.Array[ArtifactType] = js.Array(
    UNKNOWN,
    SCREENSHOT,
    DEVICE_LOG,
    MESSAGE_LOG,
    VIDEO_LOG,
    RESULT_LOG,
    SERVICE_LOG,
    WEBKIT_LOG,
    INSTRUMENTATION_OUTPUT,
    EXERCISER_MONKEY_OUTPUT,
    CALABASH_JSON_OUTPUT,
    CALABASH_PRETTY_OUTPUT,
    CALABASH_STANDARD_OUTPUT,
    CALABASH_JAVA_XML_OUTPUT,
    AUTOMATION_OUTPUT,
    APPIUM_SERVER_OUTPUT,
    APPIUM_JAVA_OUTPUT,
    APPIUM_JAVA_XML_OUTPUT,
    APPIUM_PYTHON_OUTPUT,
    APPIUM_PYTHON_XML_OUTPUT,
    EXPLORER_EVENT_LOG,
    EXPLORER_SUMMARY_LOG,
    APPLICATION_CRASH_REPORT,
    XCTEST_LOG,
    VIDEO,
    CUSTOMER_ARTIFACT,
    CUSTOMER_ARTIFACT_LOG,
    TESTSPEC_OUTPUT
  )
}

type BillingMethod = "METERED" | "UNMETERED"
object BillingMethod {
  inline val METERED: "METERED" = "METERED"
  inline val UNMETERED: "UNMETERED" = "UNMETERED"

  inline def values: js.Array[BillingMethod] = js.Array(METERED, UNMETERED)
}

type CurrencyCode = "USD"
object CurrencyCode {
  inline val USD: "USD" = "USD"

  inline def values: js.Array[CurrencyCode] = js.Array(USD)
}

type DeviceAttribute = "ARN" | "PLATFORM" | "FORM_FACTOR" | "MANUFACTURER" | "REMOTE_ACCESS_ENABLED" | "REMOTE_DEBUG_ENABLED" | "APPIUM_VERSION" | "INSTANCE_ARN" | "INSTANCE_LABELS" | "FLEET_TYPE" | "OS_VERSION" | "MODEL" | "AVAILABILITY"
object DeviceAttribute {
  inline val ARN: "ARN" = "ARN"
  inline val PLATFORM: "PLATFORM" = "PLATFORM"
  inline val FORM_FACTOR: "FORM_FACTOR" = "FORM_FACTOR"
  inline val MANUFACTURER: "MANUFACTURER" = "MANUFACTURER"
  inline val REMOTE_ACCESS_ENABLED: "REMOTE_ACCESS_ENABLED" = "REMOTE_ACCESS_ENABLED"
  inline val REMOTE_DEBUG_ENABLED: "REMOTE_DEBUG_ENABLED" = "REMOTE_DEBUG_ENABLED"
  inline val APPIUM_VERSION: "APPIUM_VERSION" = "APPIUM_VERSION"
  inline val INSTANCE_ARN: "INSTANCE_ARN" = "INSTANCE_ARN"
  inline val INSTANCE_LABELS: "INSTANCE_LABELS" = "INSTANCE_LABELS"
  inline val FLEET_TYPE: "FLEET_TYPE" = "FLEET_TYPE"
  inline val OS_VERSION: "OS_VERSION" = "OS_VERSION"
  inline val MODEL: "MODEL" = "MODEL"
  inline val AVAILABILITY: "AVAILABILITY" = "AVAILABILITY"

  inline def values: js.Array[DeviceAttribute] = js.Array(
    ARN,
    PLATFORM,
    FORM_FACTOR,
    MANUFACTURER,
    REMOTE_ACCESS_ENABLED,
    REMOTE_DEBUG_ENABLED,
    APPIUM_VERSION,
    INSTANCE_ARN,
    INSTANCE_LABELS,
    FLEET_TYPE,
    OS_VERSION,
    MODEL,
    AVAILABILITY
  )
}

type DeviceAvailability = "TEMPORARY_NOT_AVAILABLE" | "BUSY" | "AVAILABLE" | "HIGHLY_AVAILABLE"
object DeviceAvailability {
  inline val TEMPORARY_NOT_AVAILABLE: "TEMPORARY_NOT_AVAILABLE" = "TEMPORARY_NOT_AVAILABLE"
  inline val BUSY: "BUSY" = "BUSY"
  inline val AVAILABLE: "AVAILABLE" = "AVAILABLE"
  inline val HIGHLY_AVAILABLE: "HIGHLY_AVAILABLE" = "HIGHLY_AVAILABLE"

  inline def values: js.Array[DeviceAvailability] = js.Array(TEMPORARY_NOT_AVAILABLE, BUSY, AVAILABLE, HIGHLY_AVAILABLE)
}

type DeviceFilterAttribute = "ARN" | "PLATFORM" | "OS_VERSION" | "MODEL" | "AVAILABILITY" | "FORM_FACTOR" | "MANUFACTURER" | "REMOTE_ACCESS_ENABLED" | "REMOTE_DEBUG_ENABLED" | "INSTANCE_ARN" | "INSTANCE_LABELS" | "FLEET_TYPE"
object DeviceFilterAttribute {
  inline val ARN: "ARN" = "ARN"
  inline val PLATFORM: "PLATFORM" = "PLATFORM"
  inline val OS_VERSION: "OS_VERSION" = "OS_VERSION"
  inline val MODEL: "MODEL" = "MODEL"
  inline val AVAILABILITY: "AVAILABILITY" = "AVAILABILITY"
  inline val FORM_FACTOR: "FORM_FACTOR" = "FORM_FACTOR"
  inline val MANUFACTURER: "MANUFACTURER" = "MANUFACTURER"
  inline val REMOTE_ACCESS_ENABLED: "REMOTE_ACCESS_ENABLED" = "REMOTE_ACCESS_ENABLED"
  inline val REMOTE_DEBUG_ENABLED: "REMOTE_DEBUG_ENABLED" = "REMOTE_DEBUG_ENABLED"
  inline val INSTANCE_ARN: "INSTANCE_ARN" = "INSTANCE_ARN"
  inline val INSTANCE_LABELS: "INSTANCE_LABELS" = "INSTANCE_LABELS"
  inline val FLEET_TYPE: "FLEET_TYPE" = "FLEET_TYPE"

  inline def values: js.Array[DeviceFilterAttribute] = js.Array(
    ARN,
    PLATFORM,
    OS_VERSION,
    MODEL,
    AVAILABILITY,
    FORM_FACTOR,
    MANUFACTURER,
    REMOTE_ACCESS_ENABLED,
    REMOTE_DEBUG_ENABLED,
    INSTANCE_ARN,
    INSTANCE_LABELS,
    FLEET_TYPE
  )
}

type DeviceFormFactor = "PHONE" | "TABLET"
object DeviceFormFactor {
  inline val PHONE: "PHONE" = "PHONE"
  inline val TABLET: "TABLET" = "TABLET"

  inline def values: js.Array[DeviceFormFactor] = js.Array(PHONE, TABLET)
}

type DevicePlatform = "ANDROID" | "IOS"
object DevicePlatform {
  inline val ANDROID: "ANDROID" = "ANDROID"
  inline val IOS: "IOS" = "IOS"

  inline def values: js.Array[DevicePlatform] = js.Array(ANDROID, IOS)
}

type DevicePoolType = "CURATED" | "PRIVATE"
object DevicePoolType {
  inline val CURATED: "CURATED" = "CURATED"
  inline val PRIVATE: "PRIVATE" = "PRIVATE"

  inline def values: js.Array[DevicePoolType] = js.Array(CURATED, PRIVATE)
}

type ExecutionResult = "PENDING" | "PASSED" | "WARNED" | "FAILED" | "SKIPPED" | "ERRORED" | "STOPPED"
object ExecutionResult {
  inline val PENDING: "PENDING" = "PENDING"
  inline val PASSED: "PASSED" = "PASSED"
  inline val WARNED: "WARNED" = "WARNED"
  inline val FAILED: "FAILED" = "FAILED"
  inline val SKIPPED: "SKIPPED" = "SKIPPED"
  inline val ERRORED: "ERRORED" = "ERRORED"
  inline val STOPPED: "STOPPED" = "STOPPED"

  inline def values: js.Array[ExecutionResult] = js.Array(PENDING, PASSED, WARNED, FAILED, SKIPPED, ERRORED, STOPPED)
}

type ExecutionResultCode = "PARSING_FAILED" | "VPC_ENDPOINT_SETUP_FAILED"
object ExecutionResultCode {
  inline val PARSING_FAILED: "PARSING_FAILED" = "PARSING_FAILED"
  inline val VPC_ENDPOINT_SETUP_FAILED: "VPC_ENDPOINT_SETUP_FAILED" = "VPC_ENDPOINT_SETUP_FAILED"

  inline def values: js.Array[ExecutionResultCode] = js.Array(PARSING_FAILED, VPC_ENDPOINT_SETUP_FAILED)
}

type ExecutionStatus = "PENDING" | "PENDING_CONCURRENCY" | "PENDING_DEVICE" | "PROCESSING" | "SCHEDULING" | "PREPARING" | "RUNNING" | "COMPLETED" | "STOPPING"
object ExecutionStatus {
  inline val PENDING: "PENDING" = "PENDING"
  inline val PENDING_CONCURRENCY: "PENDING_CONCURRENCY" = "PENDING_CONCURRENCY"
  inline val PENDING_DEVICE: "PENDING_DEVICE" = "PENDING_DEVICE"
  inline val PROCESSING: "PROCESSING" = "PROCESSING"
  inline val SCHEDULING: "SCHEDULING" = "SCHEDULING"
  inline val PREPARING: "PREPARING" = "PREPARING"
  inline val RUNNING: "RUNNING" = "RUNNING"
  inline val COMPLETED: "COMPLETED" = "COMPLETED"
  inline val STOPPING: "STOPPING" = "STOPPING"

  inline def values: js.Array[ExecutionStatus] = js.Array(PENDING, PENDING_CONCURRENCY, PENDING_DEVICE, PROCESSING, SCHEDULING, PREPARING, RUNNING, COMPLETED, STOPPING)
}

type InstanceStatus = "IN_USE" | "PREPARING" | "AVAILABLE" | "NOT_AVAILABLE"
object InstanceStatus {
  inline val IN_USE: "IN_USE" = "IN_USE"
  inline val PREPARING: "PREPARING" = "PREPARING"
  inline val AVAILABLE: "AVAILABLE" = "AVAILABLE"
  inline val NOT_AVAILABLE: "NOT_AVAILABLE" = "NOT_AVAILABLE"

  inline def values: js.Array[InstanceStatus] = js.Array(IN_USE, PREPARING, AVAILABLE, NOT_AVAILABLE)
}

type InteractionMode = "INTERACTIVE" | "NO_VIDEO" | "VIDEO_ONLY"
object InteractionMode {
  inline val INTERACTIVE: "INTERACTIVE" = "INTERACTIVE"
  inline val NO_VIDEO: "NO_VIDEO" = "NO_VIDEO"
  inline val VIDEO_ONLY: "VIDEO_ONLY" = "VIDEO_ONLY"

  inline def values: js.Array[InteractionMode] = js.Array(INTERACTIVE, NO_VIDEO, VIDEO_ONLY)
}

type NetworkProfileType = "CURATED" | "PRIVATE"
object NetworkProfileType {
  inline val CURATED: "CURATED" = "CURATED"
  inline val PRIVATE: "PRIVATE" = "PRIVATE"

  inline def values: js.Array[NetworkProfileType] = js.Array(CURATED, PRIVATE)
}

type OfferingTransactionType = "PURCHASE" | "RENEW" | "SYSTEM"
object OfferingTransactionType {
  inline val PURCHASE: "PURCHASE" = "PURCHASE"
  inline val RENEW: "RENEW" = "RENEW"
  inline val SYSTEM: "SYSTEM" = "SYSTEM"

  inline def values: js.Array[OfferingTransactionType] = js.Array(PURCHASE, RENEW, SYSTEM)
}

type OfferingType = "RECURRING"
object OfferingType {
  inline val RECURRING: "RECURRING" = "RECURRING"

  inline def values: js.Array[OfferingType] = js.Array(RECURRING)
}

type RecurringChargeFrequency = "MONTHLY"
object RecurringChargeFrequency {
  inline val MONTHLY: "MONTHLY" = "MONTHLY"

  inline def values: js.Array[RecurringChargeFrequency] = js.Array(MONTHLY)
}

type RuleOperator = "EQUALS" | "LESS_THAN" | "LESS_THAN_OR_EQUALS" | "GREATER_THAN" | "GREATER_THAN_OR_EQUALS" | "IN" | "NOT_IN" | "CONTAINS"
object RuleOperator {
  inline val EQUALS: "EQUALS" = "EQUALS"
  inline val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  inline val LESS_THAN_OR_EQUALS: "LESS_THAN_OR_EQUALS" = "LESS_THAN_OR_EQUALS"
  inline val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  inline val GREATER_THAN_OR_EQUALS: "GREATER_THAN_OR_EQUALS" = "GREATER_THAN_OR_EQUALS"
  inline val IN: "IN" = "IN"
  inline val NOT_IN: "NOT_IN" = "NOT_IN"
  inline val CONTAINS: "CONTAINS" = "CONTAINS"

  inline def values: js.Array[RuleOperator] = js.Array(EQUALS, LESS_THAN, LESS_THAN_OR_EQUALS, GREATER_THAN, GREATER_THAN_OR_EQUALS, IN, NOT_IN, CONTAINS)
}

type SampleType = "CPU" | "MEMORY" | "THREADS" | "RX_RATE" | "TX_RATE" | "RX" | "TX" | "NATIVE_FRAMES" | "NATIVE_FPS" | "NATIVE_MIN_DRAWTIME" | "NATIVE_AVG_DRAWTIME" | "NATIVE_MAX_DRAWTIME" | "OPENGL_FRAMES" | "OPENGL_FPS" | "OPENGL_MIN_DRAWTIME" | "OPENGL_AVG_DRAWTIME" | "OPENGL_MAX_DRAWTIME"
object SampleType {
  inline val CPU: "CPU" = "CPU"
  inline val MEMORY: "MEMORY" = "MEMORY"
  inline val THREADS: "THREADS" = "THREADS"
  inline val RX_RATE: "RX_RATE" = "RX_RATE"
  inline val TX_RATE: "TX_RATE" = "TX_RATE"
  inline val RX: "RX" = "RX"
  inline val TX: "TX" = "TX"
  inline val NATIVE_FRAMES: "NATIVE_FRAMES" = "NATIVE_FRAMES"
  inline val NATIVE_FPS: "NATIVE_FPS" = "NATIVE_FPS"
  inline val NATIVE_MIN_DRAWTIME: "NATIVE_MIN_DRAWTIME" = "NATIVE_MIN_DRAWTIME"
  inline val NATIVE_AVG_DRAWTIME: "NATIVE_AVG_DRAWTIME" = "NATIVE_AVG_DRAWTIME"
  inline val NATIVE_MAX_DRAWTIME: "NATIVE_MAX_DRAWTIME" = "NATIVE_MAX_DRAWTIME"
  inline val OPENGL_FRAMES: "OPENGL_FRAMES" = "OPENGL_FRAMES"
  inline val OPENGL_FPS: "OPENGL_FPS" = "OPENGL_FPS"
  inline val OPENGL_MIN_DRAWTIME: "OPENGL_MIN_DRAWTIME" = "OPENGL_MIN_DRAWTIME"
  inline val OPENGL_AVG_DRAWTIME: "OPENGL_AVG_DRAWTIME" = "OPENGL_AVG_DRAWTIME"
  inline val OPENGL_MAX_DRAWTIME: "OPENGL_MAX_DRAWTIME" = "OPENGL_MAX_DRAWTIME"

  inline def values: js.Array[SampleType] = js.Array(
    CPU,
    MEMORY,
    THREADS,
    RX_RATE,
    TX_RATE,
    RX,
    TX,
    NATIVE_FRAMES,
    NATIVE_FPS,
    NATIVE_MIN_DRAWTIME,
    NATIVE_AVG_DRAWTIME,
    NATIVE_MAX_DRAWTIME,
    OPENGL_FRAMES,
    OPENGL_FPS,
    OPENGL_MIN_DRAWTIME,
    OPENGL_AVG_DRAWTIME,
    OPENGL_MAX_DRAWTIME
  )
}

type TestGridSessionArtifactCategory = "VIDEO" | "LOG"
object TestGridSessionArtifactCategory {
  inline val VIDEO: "VIDEO" = "VIDEO"
  inline val LOG: "LOG" = "LOG"

  inline def values: js.Array[TestGridSessionArtifactCategory] = js.Array(VIDEO, LOG)
}

type TestGridSessionArtifactType = "UNKNOWN" | "VIDEO" | "SELENIUM_LOG"
object TestGridSessionArtifactType {
  inline val UNKNOWN: "UNKNOWN" = "UNKNOWN"
  inline val VIDEO: "VIDEO" = "VIDEO"
  inline val SELENIUM_LOG: "SELENIUM_LOG" = "SELENIUM_LOG"

  inline def values: js.Array[TestGridSessionArtifactType] = js.Array(UNKNOWN, VIDEO, SELENIUM_LOG)
}

type TestGridSessionStatus = "ACTIVE" | "CLOSED" | "ERRORED"
object TestGridSessionStatus {
  inline val ACTIVE: "ACTIVE" = "ACTIVE"
  inline val CLOSED: "CLOSED" = "CLOSED"
  inline val ERRORED: "ERRORED" = "ERRORED"

  inline def values: js.Array[TestGridSessionStatus] = js.Array(ACTIVE, CLOSED, ERRORED)
}

type TestType = "BUILTIN_FUZZ" | "BUILTIN_EXPLORER" | "WEB_PERFORMANCE_PROFILE" | "APPIUM_JAVA_JUNIT" | "APPIUM_JAVA_TESTNG" | "APPIUM_PYTHON" | "APPIUM_NODE" | "APPIUM_RUBY" | "APPIUM_WEB_JAVA_JUNIT" | "APPIUM_WEB_JAVA_TESTNG" | "APPIUM_WEB_PYTHON" | "APPIUM_WEB_NODE" | "APPIUM_WEB_RUBY" | "CALABASH" | "INSTRUMENTATION" | "UIAUTOMATION" | "UIAUTOMATOR" | "XCTEST" | "XCTEST_UI" | "REMOTE_ACCESS_RECORD" | "REMOTE_ACCESS_REPLAY"
object TestType {
  inline val BUILTIN_FUZZ: "BUILTIN_FUZZ" = "BUILTIN_FUZZ"
  inline val BUILTIN_EXPLORER: "BUILTIN_EXPLORER" = "BUILTIN_EXPLORER"
  inline val WEB_PERFORMANCE_PROFILE: "WEB_PERFORMANCE_PROFILE" = "WEB_PERFORMANCE_PROFILE"
  inline val APPIUM_JAVA_JUNIT: "APPIUM_JAVA_JUNIT" = "APPIUM_JAVA_JUNIT"
  inline val APPIUM_JAVA_TESTNG: "APPIUM_JAVA_TESTNG" = "APPIUM_JAVA_TESTNG"
  inline val APPIUM_PYTHON: "APPIUM_PYTHON" = "APPIUM_PYTHON"
  inline val APPIUM_NODE: "APPIUM_NODE" = "APPIUM_NODE"
  inline val APPIUM_RUBY: "APPIUM_RUBY" = "APPIUM_RUBY"
  inline val APPIUM_WEB_JAVA_JUNIT: "APPIUM_WEB_JAVA_JUNIT" = "APPIUM_WEB_JAVA_JUNIT"
  inline val APPIUM_WEB_JAVA_TESTNG: "APPIUM_WEB_JAVA_TESTNG" = "APPIUM_WEB_JAVA_TESTNG"
  inline val APPIUM_WEB_PYTHON: "APPIUM_WEB_PYTHON" = "APPIUM_WEB_PYTHON"
  inline val APPIUM_WEB_NODE: "APPIUM_WEB_NODE" = "APPIUM_WEB_NODE"
  inline val APPIUM_WEB_RUBY: "APPIUM_WEB_RUBY" = "APPIUM_WEB_RUBY"
  inline val CALABASH: "CALABASH" = "CALABASH"
  inline val INSTRUMENTATION: "INSTRUMENTATION" = "INSTRUMENTATION"
  inline val UIAUTOMATION: "UIAUTOMATION" = "UIAUTOMATION"
  inline val UIAUTOMATOR: "UIAUTOMATOR" = "UIAUTOMATOR"
  inline val XCTEST: "XCTEST" = "XCTEST"
  inline val XCTEST_UI: "XCTEST_UI" = "XCTEST_UI"
  inline val REMOTE_ACCESS_RECORD: "REMOTE_ACCESS_RECORD" = "REMOTE_ACCESS_RECORD"
  inline val REMOTE_ACCESS_REPLAY: "REMOTE_ACCESS_REPLAY" = "REMOTE_ACCESS_REPLAY"

  inline def values: js.Array[TestType] = js.Array(
    BUILTIN_FUZZ,
    BUILTIN_EXPLORER,
    WEB_PERFORMANCE_PROFILE,
    APPIUM_JAVA_JUNIT,
    APPIUM_JAVA_TESTNG,
    APPIUM_PYTHON,
    APPIUM_NODE,
    APPIUM_RUBY,
    APPIUM_WEB_JAVA_JUNIT,
    APPIUM_WEB_JAVA_TESTNG,
    APPIUM_WEB_PYTHON,
    APPIUM_WEB_NODE,
    APPIUM_WEB_RUBY,
    CALABASH,
    INSTRUMENTATION,
    UIAUTOMATION,
    UIAUTOMATOR,
    XCTEST,
    XCTEST_UI,
    REMOTE_ACCESS_RECORD,
    REMOTE_ACCESS_REPLAY
  )
}

type UploadCategory = "CURATED" | "PRIVATE"
object UploadCategory {
  inline val CURATED: "CURATED" = "CURATED"
  inline val PRIVATE: "PRIVATE" = "PRIVATE"

  inline def values: js.Array[UploadCategory] = js.Array(CURATED, PRIVATE)
}

type UploadStatus = "INITIALIZED" | "PROCESSING" | "SUCCEEDED" | "FAILED"
object UploadStatus {
  inline val INITIALIZED: "INITIALIZED" = "INITIALIZED"
  inline val PROCESSING: "PROCESSING" = "PROCESSING"
  inline val SUCCEEDED: "SUCCEEDED" = "SUCCEEDED"
  inline val FAILED: "FAILED" = "FAILED"

  inline def values: js.Array[UploadStatus] = js.Array(INITIALIZED, PROCESSING, SUCCEEDED, FAILED)
}

type UploadType = "ANDROID_APP" | "IOS_APP" | "WEB_APP" | "EXTERNAL_DATA" | "APPIUM_JAVA_JUNIT_TEST_PACKAGE" | "APPIUM_JAVA_TESTNG_TEST_PACKAGE" | "APPIUM_PYTHON_TEST_PACKAGE" | "APPIUM_NODE_TEST_PACKAGE" | "APPIUM_RUBY_TEST_PACKAGE" | "APPIUM_WEB_JAVA_JUNIT_TEST_PACKAGE" | "APPIUM_WEB_JAVA_TESTNG_TEST_PACKAGE" | "APPIUM_WEB_PYTHON_TEST_PACKAGE" | "APPIUM_WEB_NODE_TEST_PACKAGE" | "APPIUM_WEB_RUBY_TEST_PACKAGE" | "CALABASH_TEST_PACKAGE" | "INSTRUMENTATION_TEST_PACKAGE" | "UIAUTOMATION_TEST_PACKAGE" | "UIAUTOMATOR_TEST_PACKAGE" | "XCTEST_TEST_PACKAGE" | "XCTEST_UI_TEST_PACKAGE" | "APPIUM_JAVA_JUNIT_TEST_SPEC" | "APPIUM_JAVA_TESTNG_TEST_SPEC" | "APPIUM_PYTHON_TEST_SPEC" | "APPIUM_NODE_TEST_SPEC" | "APPIUM_RUBY_TEST_SPEC" | "APPIUM_WEB_JAVA_JUNIT_TEST_SPEC" | "APPIUM_WEB_JAVA_TESTNG_TEST_SPEC" | "APPIUM_WEB_PYTHON_TEST_SPEC" | "APPIUM_WEB_NODE_TEST_SPEC" | "APPIUM_WEB_RUBY_TEST_SPEC" | "INSTRUMENTATION_TEST_SPEC" | "XCTEST_UI_TEST_SPEC"
object UploadType {
  inline val ANDROID_APP: "ANDROID_APP" = "ANDROID_APP"
  inline val IOS_APP: "IOS_APP" = "IOS_APP"
  inline val WEB_APP: "WEB_APP" = "WEB_APP"
  inline val EXTERNAL_DATA: "EXTERNAL_DATA" = "EXTERNAL_DATA"
  inline val APPIUM_JAVA_JUNIT_TEST_PACKAGE: "APPIUM_JAVA_JUNIT_TEST_PACKAGE" = "APPIUM_JAVA_JUNIT_TEST_PACKAGE"
  inline val APPIUM_JAVA_TESTNG_TEST_PACKAGE: "APPIUM_JAVA_TESTNG_TEST_PACKAGE" = "APPIUM_JAVA_TESTNG_TEST_PACKAGE"
  inline val APPIUM_PYTHON_TEST_PACKAGE: "APPIUM_PYTHON_TEST_PACKAGE" = "APPIUM_PYTHON_TEST_PACKAGE"
  inline val APPIUM_NODE_TEST_PACKAGE: "APPIUM_NODE_TEST_PACKAGE" = "APPIUM_NODE_TEST_PACKAGE"
  inline val APPIUM_RUBY_TEST_PACKAGE: "APPIUM_RUBY_TEST_PACKAGE" = "APPIUM_RUBY_TEST_PACKAGE"
  inline val APPIUM_WEB_JAVA_JUNIT_TEST_PACKAGE: "APPIUM_WEB_JAVA_JUNIT_TEST_PACKAGE" = "APPIUM_WEB_JAVA_JUNIT_TEST_PACKAGE"
  inline val APPIUM_WEB_JAVA_TESTNG_TEST_PACKAGE: "APPIUM_WEB_JAVA_TESTNG_TEST_PACKAGE" = "APPIUM_WEB_JAVA_TESTNG_TEST_PACKAGE"
  inline val APPIUM_WEB_PYTHON_TEST_PACKAGE: "APPIUM_WEB_PYTHON_TEST_PACKAGE" = "APPIUM_WEB_PYTHON_TEST_PACKAGE"
  inline val APPIUM_WEB_NODE_TEST_PACKAGE: "APPIUM_WEB_NODE_TEST_PACKAGE" = "APPIUM_WEB_NODE_TEST_PACKAGE"
  inline val APPIUM_WEB_RUBY_TEST_PACKAGE: "APPIUM_WEB_RUBY_TEST_PACKAGE" = "APPIUM_WEB_RUBY_TEST_PACKAGE"
  inline val CALABASH_TEST_PACKAGE: "CALABASH_TEST_PACKAGE" = "CALABASH_TEST_PACKAGE"
  inline val INSTRUMENTATION_TEST_PACKAGE: "INSTRUMENTATION_TEST_PACKAGE" = "INSTRUMENTATION_TEST_PACKAGE"
  inline val UIAUTOMATION_TEST_PACKAGE: "UIAUTOMATION_TEST_PACKAGE" = "UIAUTOMATION_TEST_PACKAGE"
  inline val UIAUTOMATOR_TEST_PACKAGE: "UIAUTOMATOR_TEST_PACKAGE" = "UIAUTOMATOR_TEST_PACKAGE"
  inline val XCTEST_TEST_PACKAGE: "XCTEST_TEST_PACKAGE" = "XCTEST_TEST_PACKAGE"
  inline val XCTEST_UI_TEST_PACKAGE: "XCTEST_UI_TEST_PACKAGE" = "XCTEST_UI_TEST_PACKAGE"
  inline val APPIUM_JAVA_JUNIT_TEST_SPEC: "APPIUM_JAVA_JUNIT_TEST_SPEC" = "APPIUM_JAVA_JUNIT_TEST_SPEC"
  inline val APPIUM_JAVA_TESTNG_TEST_SPEC: "APPIUM_JAVA_TESTNG_TEST_SPEC" = "APPIUM_JAVA_TESTNG_TEST_SPEC"
  inline val APPIUM_PYTHON_TEST_SPEC: "APPIUM_PYTHON_TEST_SPEC" = "APPIUM_PYTHON_TEST_SPEC"
  inline val APPIUM_NODE_TEST_SPEC: "APPIUM_NODE_TEST_SPEC" = "APPIUM_NODE_TEST_SPEC"
  inline val APPIUM_RUBY_TEST_SPEC: "APPIUM_RUBY_TEST_SPEC" = "APPIUM_RUBY_TEST_SPEC"
  inline val APPIUM_WEB_JAVA_JUNIT_TEST_SPEC: "APPIUM_WEB_JAVA_JUNIT_TEST_SPEC" = "APPIUM_WEB_JAVA_JUNIT_TEST_SPEC"
  inline val APPIUM_WEB_JAVA_TESTNG_TEST_SPEC: "APPIUM_WEB_JAVA_TESTNG_TEST_SPEC" = "APPIUM_WEB_JAVA_TESTNG_TEST_SPEC"
  inline val APPIUM_WEB_PYTHON_TEST_SPEC: "APPIUM_WEB_PYTHON_TEST_SPEC" = "APPIUM_WEB_PYTHON_TEST_SPEC"
  inline val APPIUM_WEB_NODE_TEST_SPEC: "APPIUM_WEB_NODE_TEST_SPEC" = "APPIUM_WEB_NODE_TEST_SPEC"
  inline val APPIUM_WEB_RUBY_TEST_SPEC: "APPIUM_WEB_RUBY_TEST_SPEC" = "APPIUM_WEB_RUBY_TEST_SPEC"
  inline val INSTRUMENTATION_TEST_SPEC: "INSTRUMENTATION_TEST_SPEC" = "INSTRUMENTATION_TEST_SPEC"
  inline val XCTEST_UI_TEST_SPEC: "XCTEST_UI_TEST_SPEC" = "XCTEST_UI_TEST_SPEC"

  inline def values: js.Array[UploadType] = js.Array(
    ANDROID_APP,
    IOS_APP,
    WEB_APP,
    EXTERNAL_DATA,
    APPIUM_JAVA_JUNIT_TEST_PACKAGE,
    APPIUM_JAVA_TESTNG_TEST_PACKAGE,
    APPIUM_PYTHON_TEST_PACKAGE,
    APPIUM_NODE_TEST_PACKAGE,
    APPIUM_RUBY_TEST_PACKAGE,
    APPIUM_WEB_JAVA_JUNIT_TEST_PACKAGE,
    APPIUM_WEB_JAVA_TESTNG_TEST_PACKAGE,
    APPIUM_WEB_PYTHON_TEST_PACKAGE,
    APPIUM_WEB_NODE_TEST_PACKAGE,
    APPIUM_WEB_RUBY_TEST_PACKAGE,
    CALABASH_TEST_PACKAGE,
    INSTRUMENTATION_TEST_PACKAGE,
    UIAUTOMATION_TEST_PACKAGE,
    UIAUTOMATOR_TEST_PACKAGE,
    XCTEST_TEST_PACKAGE,
    XCTEST_UI_TEST_PACKAGE,
    APPIUM_JAVA_JUNIT_TEST_SPEC,
    APPIUM_JAVA_TESTNG_TEST_SPEC,
    APPIUM_PYTHON_TEST_SPEC,
    APPIUM_NODE_TEST_SPEC,
    APPIUM_RUBY_TEST_SPEC,
    APPIUM_WEB_JAVA_JUNIT_TEST_SPEC,
    APPIUM_WEB_JAVA_TESTNG_TEST_SPEC,
    APPIUM_WEB_PYTHON_TEST_SPEC,
    APPIUM_WEB_NODE_TEST_SPEC,
    APPIUM_WEB_RUBY_TEST_SPEC,
    INSTRUMENTATION_TEST_SPEC,
    XCTEST_UI_TEST_SPEC
  )
}
