package facade.amazonaws.services.servicequotas

import scalajs._

type ErrorCode = "DEPENDENCY_ACCESS_DENIED_ERROR" | "DEPENDENCY_THROTTLING_ERROR" | "DEPENDENCY_SERVICE_ERROR" | "SERVICE_QUOTA_NOT_AVAILABLE_ERROR"
object ErrorCode {
  val DEPENDENCY_ACCESS_DENIED_ERROR: "DEPENDENCY_ACCESS_DENIED_ERROR" = "DEPENDENCY_ACCESS_DENIED_ERROR"
  val DEPENDENCY_THROTTLING_ERROR: "DEPENDENCY_THROTTLING_ERROR" = "DEPENDENCY_THROTTLING_ERROR"
  val DEPENDENCY_SERVICE_ERROR: "DEPENDENCY_SERVICE_ERROR" = "DEPENDENCY_SERVICE_ERROR"
  val SERVICE_QUOTA_NOT_AVAILABLE_ERROR: "SERVICE_QUOTA_NOT_AVAILABLE_ERROR" = "SERVICE_QUOTA_NOT_AVAILABLE_ERROR"

  @inline def values = js.Array[ErrorCode](DEPENDENCY_ACCESS_DENIED_ERROR, DEPENDENCY_THROTTLING_ERROR, DEPENDENCY_SERVICE_ERROR, SERVICE_QUOTA_NOT_AVAILABLE_ERROR)
}

type PeriodUnit = "MICROSECOND" | "MILLISECOND" | "SECOND" | "MINUTE" | "HOUR" | "DAY" | "WEEK"
object PeriodUnit {
  val MICROSECOND: "MICROSECOND" = "MICROSECOND"
  val MILLISECOND: "MILLISECOND" = "MILLISECOND"
  val SECOND: "SECOND" = "SECOND"
  val MINUTE: "MINUTE" = "MINUTE"
  val HOUR: "HOUR" = "HOUR"
  val DAY: "DAY" = "DAY"
  val WEEK: "WEEK" = "WEEK"

  @inline def values = js.Array[PeriodUnit](MICROSECOND, MILLISECOND, SECOND, MINUTE, HOUR, DAY, WEEK)
}

type RequestStatus = "PENDING" | "CASE_OPENED" | "APPROVED" | "DENIED" | "CASE_CLOSED"
object RequestStatus {
  val PENDING: "PENDING" = "PENDING"
  val CASE_OPENED: "CASE_OPENED" = "CASE_OPENED"
  val APPROVED: "APPROVED" = "APPROVED"
  val DENIED: "DENIED" = "DENIED"
  val CASE_CLOSED: "CASE_CLOSED" = "CASE_CLOSED"

  @inline def values = js.Array[RequestStatus](PENDING, CASE_OPENED, APPROVED, DENIED, CASE_CLOSED)
}

type ServiceQuotaTemplateAssociationStatus = "ASSOCIATED" | "DISASSOCIATED"
object ServiceQuotaTemplateAssociationStatus {
  val ASSOCIATED: "ASSOCIATED" = "ASSOCIATED"
  val DISASSOCIATED: "DISASSOCIATED" = "DISASSOCIATED"

  @inline def values = js.Array[ServiceQuotaTemplateAssociationStatus](ASSOCIATED, DISASSOCIATED)
}
