package facade.amazonaws.services.backup

import scalajs._

type BackupJobState = "CREATED" | "PENDING" | "RUNNING" | "ABORTING" | "ABORTED" | "COMPLETED" | "FAILED" | "EXPIRED"
object BackupJobState {
  inline val CREATED: "CREATED" = "CREATED"
  inline val PENDING: "PENDING" = "PENDING"
  inline val RUNNING: "RUNNING" = "RUNNING"
  inline val ABORTING: "ABORTING" = "ABORTING"
  inline val ABORTED: "ABORTED" = "ABORTED"
  inline val COMPLETED: "COMPLETED" = "COMPLETED"
  inline val FAILED: "FAILED" = "FAILED"
  inline val EXPIRED: "EXPIRED" = "EXPIRED"

  inline def values: js.Array[BackupJobState] = js.Array(CREATED, PENDING, RUNNING, ABORTING, ABORTED, COMPLETED, FAILED, EXPIRED)
}

type BackupVaultEvent = "BACKUP_JOB_STARTED" | "BACKUP_JOB_COMPLETED" | "BACKUP_JOB_SUCCESSFUL" | "BACKUP_JOB_FAILED" | "BACKUP_JOB_EXPIRED" | "RESTORE_JOB_STARTED" | "RESTORE_JOB_COMPLETED" | "RESTORE_JOB_SUCCESSFUL" | "RESTORE_JOB_FAILED" | "COPY_JOB_STARTED" | "COPY_JOB_SUCCESSFUL" | "COPY_JOB_FAILED" | "RECOVERY_POINT_MODIFIED" | "BACKUP_PLAN_CREATED" | "BACKUP_PLAN_MODIFIED"
object BackupVaultEvent {
  inline val BACKUP_JOB_STARTED: "BACKUP_JOB_STARTED" = "BACKUP_JOB_STARTED"
  inline val BACKUP_JOB_COMPLETED: "BACKUP_JOB_COMPLETED" = "BACKUP_JOB_COMPLETED"
  inline val BACKUP_JOB_SUCCESSFUL: "BACKUP_JOB_SUCCESSFUL" = "BACKUP_JOB_SUCCESSFUL"
  inline val BACKUP_JOB_FAILED: "BACKUP_JOB_FAILED" = "BACKUP_JOB_FAILED"
  inline val BACKUP_JOB_EXPIRED: "BACKUP_JOB_EXPIRED" = "BACKUP_JOB_EXPIRED"
  inline val RESTORE_JOB_STARTED: "RESTORE_JOB_STARTED" = "RESTORE_JOB_STARTED"
  inline val RESTORE_JOB_COMPLETED: "RESTORE_JOB_COMPLETED" = "RESTORE_JOB_COMPLETED"
  inline val RESTORE_JOB_SUCCESSFUL: "RESTORE_JOB_SUCCESSFUL" = "RESTORE_JOB_SUCCESSFUL"
  inline val RESTORE_JOB_FAILED: "RESTORE_JOB_FAILED" = "RESTORE_JOB_FAILED"
  inline val COPY_JOB_STARTED: "COPY_JOB_STARTED" = "COPY_JOB_STARTED"
  inline val COPY_JOB_SUCCESSFUL: "COPY_JOB_SUCCESSFUL" = "COPY_JOB_SUCCESSFUL"
  inline val COPY_JOB_FAILED: "COPY_JOB_FAILED" = "COPY_JOB_FAILED"
  inline val RECOVERY_POINT_MODIFIED: "RECOVERY_POINT_MODIFIED" = "RECOVERY_POINT_MODIFIED"
  inline val BACKUP_PLAN_CREATED: "BACKUP_PLAN_CREATED" = "BACKUP_PLAN_CREATED"
  inline val BACKUP_PLAN_MODIFIED: "BACKUP_PLAN_MODIFIED" = "BACKUP_PLAN_MODIFIED"

  inline def values: js.Array[BackupVaultEvent] = js.Array(
    BACKUP_JOB_STARTED,
    BACKUP_JOB_COMPLETED,
    BACKUP_JOB_SUCCESSFUL,
    BACKUP_JOB_FAILED,
    BACKUP_JOB_EXPIRED,
    RESTORE_JOB_STARTED,
    RESTORE_JOB_COMPLETED,
    RESTORE_JOB_SUCCESSFUL,
    RESTORE_JOB_FAILED,
    COPY_JOB_STARTED,
    COPY_JOB_SUCCESSFUL,
    COPY_JOB_FAILED,
    RECOVERY_POINT_MODIFIED,
    BACKUP_PLAN_CREATED,
    BACKUP_PLAN_MODIFIED
  )
}

type ConditionType = "STRINGEQUALS"
object ConditionType {
  inline val STRINGEQUALS: "STRINGEQUALS" = "STRINGEQUALS"

  inline def values: js.Array[ConditionType] = js.Array(STRINGEQUALS)
}

type CopyJobState = "CREATED" | "RUNNING" | "COMPLETED" | "FAILED"
object CopyJobState {
  inline val CREATED: "CREATED" = "CREATED"
  inline val RUNNING: "RUNNING" = "RUNNING"
  inline val COMPLETED: "COMPLETED" = "COMPLETED"
  inline val FAILED: "FAILED" = "FAILED"

  inline def values: js.Array[CopyJobState] = js.Array(CREATED, RUNNING, COMPLETED, FAILED)
}

type RecoveryPointStatus = "COMPLETED" | "PARTIAL" | "DELETING" | "EXPIRED"
object RecoveryPointStatus {
  inline val COMPLETED: "COMPLETED" = "COMPLETED"
  inline val PARTIAL: "PARTIAL" = "PARTIAL"
  inline val DELETING: "DELETING" = "DELETING"
  inline val EXPIRED: "EXPIRED" = "EXPIRED"

  inline def values: js.Array[RecoveryPointStatus] = js.Array(COMPLETED, PARTIAL, DELETING, EXPIRED)
}

type RestoreJobStatus = "PENDING" | "RUNNING" | "COMPLETED" | "ABORTED" | "FAILED"
object RestoreJobStatus {
  inline val PENDING: "PENDING" = "PENDING"
  inline val RUNNING: "RUNNING" = "RUNNING"
  inline val COMPLETED: "COMPLETED" = "COMPLETED"
  inline val ABORTED: "ABORTED" = "ABORTED"
  inline val FAILED: "FAILED" = "FAILED"

  inline def values: js.Array[RestoreJobStatus] = js.Array(PENDING, RUNNING, COMPLETED, ABORTED, FAILED)
}

type StorageClass = "WARM" | "COLD" | "DELETED"
object StorageClass {
  inline val WARM: "WARM" = "WARM"
  inline val COLD: "COLD" = "COLD"
  inline val DELETED: "DELETED" = "DELETED"

  inline def values: js.Array[StorageClass] = js.Array(WARM, COLD, DELETED)
}
