package facade.amazonaws.services.organizations

import scalajs._

type AccountJoinedMethod = "INVITED" | "CREATED"
object AccountJoinedMethod {
  val INVITED: "INVITED" = "INVITED"
  val CREATED: "CREATED" = "CREATED"

  @inline def values = js.Array[AccountJoinedMethod](INVITED, CREATED)
}

type AccountStatus = "ACTIVE" | "SUSPENDED"
object AccountStatus {
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val SUSPENDED: "SUSPENDED" = "SUSPENDED"

  @inline def values = js.Array[AccountStatus](ACTIVE, SUSPENDED)
}

type ActionType = "INVITE" | "ENABLE_ALL_FEATURES" | "APPROVE_ALL_FEATURES" | "ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE"
object ActionType {
  val INVITE: "INVITE" = "INVITE"
  val ENABLE_ALL_FEATURES: "ENABLE_ALL_FEATURES" = "ENABLE_ALL_FEATURES"
  val APPROVE_ALL_FEATURES: "APPROVE_ALL_FEATURES" = "APPROVE_ALL_FEATURES"
  val ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE: "ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE" = "ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE"

  @inline def values = js.Array[ActionType](INVITE, ENABLE_ALL_FEATURES, APPROVE_ALL_FEATURES, ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE)
}

type ChildType = "ACCOUNT" | "ORGANIZATIONAL_UNIT"
object ChildType {
  val ACCOUNT: "ACCOUNT" = "ACCOUNT"
  val ORGANIZATIONAL_UNIT: "ORGANIZATIONAL_UNIT" = "ORGANIZATIONAL_UNIT"

  @inline def values = js.Array[ChildType](ACCOUNT, ORGANIZATIONAL_UNIT)
}

type CreateAccountFailureReason = "ACCOUNT_LIMIT_EXCEEDED" | "EMAIL_ALREADY_EXISTS" | "INVALID_ADDRESS" | "INVALID_EMAIL" | "CONCURRENT_ACCOUNT_MODIFICATION" | "INTERNAL_FAILURE" | "GOVCLOUD_ACCOUNT_ALREADY_EXISTS" | "MISSING_BUSINESS_VALIDATION" | "FAILED_BUSINESS_VALIDATION" | "PENDING_BUSINESS_VALIDATION" | "INVALID_IDENTITY_FOR_BUSINESS_VALIDATION" | "UNKNOWN_BUSINESS_VALIDATION" | "MISSING_PAYMENT_INSTRUMENT"
object CreateAccountFailureReason {
  val ACCOUNT_LIMIT_EXCEEDED: "ACCOUNT_LIMIT_EXCEEDED" = "ACCOUNT_LIMIT_EXCEEDED"
  val EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS" = "EMAIL_ALREADY_EXISTS"
  val INVALID_ADDRESS: "INVALID_ADDRESS" = "INVALID_ADDRESS"
  val INVALID_EMAIL: "INVALID_EMAIL" = "INVALID_EMAIL"
  val CONCURRENT_ACCOUNT_MODIFICATION: "CONCURRENT_ACCOUNT_MODIFICATION" = "CONCURRENT_ACCOUNT_MODIFICATION"
  val INTERNAL_FAILURE: "INTERNAL_FAILURE" = "INTERNAL_FAILURE"
  val GOVCLOUD_ACCOUNT_ALREADY_EXISTS: "GOVCLOUD_ACCOUNT_ALREADY_EXISTS" = "GOVCLOUD_ACCOUNT_ALREADY_EXISTS"
  val MISSING_BUSINESS_VALIDATION: "MISSING_BUSINESS_VALIDATION" = "MISSING_BUSINESS_VALIDATION"
  val FAILED_BUSINESS_VALIDATION: "FAILED_BUSINESS_VALIDATION" = "FAILED_BUSINESS_VALIDATION"
  val PENDING_BUSINESS_VALIDATION: "PENDING_BUSINESS_VALIDATION" = "PENDING_BUSINESS_VALIDATION"
  val INVALID_IDENTITY_FOR_BUSINESS_VALIDATION: "INVALID_IDENTITY_FOR_BUSINESS_VALIDATION" = "INVALID_IDENTITY_FOR_BUSINESS_VALIDATION"
  val UNKNOWN_BUSINESS_VALIDATION: "UNKNOWN_BUSINESS_VALIDATION" = "UNKNOWN_BUSINESS_VALIDATION"
  val MISSING_PAYMENT_INSTRUMENT: "MISSING_PAYMENT_INSTRUMENT" = "MISSING_PAYMENT_INSTRUMENT"

  @inline def values = js.Array[CreateAccountFailureReason](
    ACCOUNT_LIMIT_EXCEEDED,
    EMAIL_ALREADY_EXISTS,
    INVALID_ADDRESS,
    INVALID_EMAIL,
    CONCURRENT_ACCOUNT_MODIFICATION,
    INTERNAL_FAILURE,
    GOVCLOUD_ACCOUNT_ALREADY_EXISTS,
    MISSING_BUSINESS_VALIDATION,
    FAILED_BUSINESS_VALIDATION,
    PENDING_BUSINESS_VALIDATION,
    INVALID_IDENTITY_FOR_BUSINESS_VALIDATION,
    UNKNOWN_BUSINESS_VALIDATION,
    MISSING_PAYMENT_INSTRUMENT
  )
}

type CreateAccountState = "IN_PROGRESS" | "SUCCEEDED" | "FAILED"
object CreateAccountState {
  val IN_PROGRESS: "IN_PROGRESS" = "IN_PROGRESS"
  val SUCCEEDED: "SUCCEEDED" = "SUCCEEDED"
  val FAILED: "FAILED" = "FAILED"

  @inline def values = js.Array[CreateAccountState](IN_PROGRESS, SUCCEEDED, FAILED)
}

type EffectivePolicyType = "TAG_POLICY" | "BACKUP_POLICY" | "AISERVICES_OPT_OUT_POLICY"
object EffectivePolicyType {
  val TAG_POLICY: "TAG_POLICY" = "TAG_POLICY"
  val BACKUP_POLICY: "BACKUP_POLICY" = "BACKUP_POLICY"
  val AISERVICES_OPT_OUT_POLICY: "AISERVICES_OPT_OUT_POLICY" = "AISERVICES_OPT_OUT_POLICY"

  @inline def values = js.Array[EffectivePolicyType](TAG_POLICY, BACKUP_POLICY, AISERVICES_OPT_OUT_POLICY)
}

type HandshakePartyType = "ACCOUNT" | "ORGANIZATION" | "EMAIL"
object HandshakePartyType {
  val ACCOUNT: "ACCOUNT" = "ACCOUNT"
  val ORGANIZATION: "ORGANIZATION" = "ORGANIZATION"
  val EMAIL: "EMAIL" = "EMAIL"

  @inline def values = js.Array[HandshakePartyType](ACCOUNT, ORGANIZATION, EMAIL)
}

type HandshakeResourceType = "ACCOUNT" | "ORGANIZATION" | "ORGANIZATION_FEATURE_SET" | "EMAIL" | "MASTER_EMAIL" | "MASTER_NAME" | "NOTES" | "PARENT_HANDSHAKE"
object HandshakeResourceType {
  val ACCOUNT: "ACCOUNT" = "ACCOUNT"
  val ORGANIZATION: "ORGANIZATION" = "ORGANIZATION"
  val ORGANIZATION_FEATURE_SET: "ORGANIZATION_FEATURE_SET" = "ORGANIZATION_FEATURE_SET"
  val EMAIL: "EMAIL" = "EMAIL"
  val MASTER_EMAIL: "MASTER_EMAIL" = "MASTER_EMAIL"
  val MASTER_NAME: "MASTER_NAME" = "MASTER_NAME"
  val NOTES: "NOTES" = "NOTES"
  val PARENT_HANDSHAKE: "PARENT_HANDSHAKE" = "PARENT_HANDSHAKE"

  @inline def values = js.Array[HandshakeResourceType](ACCOUNT, ORGANIZATION, ORGANIZATION_FEATURE_SET, EMAIL, MASTER_EMAIL, MASTER_NAME, NOTES, PARENT_HANDSHAKE)
}

type HandshakeState = "REQUESTED" | "OPEN" | "CANCELED" | "ACCEPTED" | "DECLINED" | "EXPIRED"
object HandshakeState {
  val REQUESTED: "REQUESTED" = "REQUESTED"
  val OPEN: "OPEN" = "OPEN"
  val CANCELED: "CANCELED" = "CANCELED"
  val ACCEPTED: "ACCEPTED" = "ACCEPTED"
  val DECLINED: "DECLINED" = "DECLINED"
  val EXPIRED: "EXPIRED" = "EXPIRED"

  @inline def values = js.Array[HandshakeState](REQUESTED, OPEN, CANCELED, ACCEPTED, DECLINED, EXPIRED)
}

type IAMUserAccessToBilling = "ALLOW" | "DENY"
object IAMUserAccessToBilling {
  val ALLOW: "ALLOW" = "ALLOW"
  val DENY: "DENY" = "DENY"

  @inline def values = js.Array[IAMUserAccessToBilling](ALLOW, DENY)
}

type OrganizationFeatureSet = "ALL" | "CONSOLIDATED_BILLING"
object OrganizationFeatureSet {
  val ALL: "ALL" = "ALL"
  val CONSOLIDATED_BILLING: "CONSOLIDATED_BILLING" = "CONSOLIDATED_BILLING"

  @inline def values = js.Array[OrganizationFeatureSet](ALL, CONSOLIDATED_BILLING)
}

type ParentType = "ROOT" | "ORGANIZATIONAL_UNIT"
object ParentType {
  val ROOT: "ROOT" = "ROOT"
  val ORGANIZATIONAL_UNIT: "ORGANIZATIONAL_UNIT" = "ORGANIZATIONAL_UNIT"

  @inline def values = js.Array[ParentType](ROOT, ORGANIZATIONAL_UNIT)
}

type PolicyType = "SERVICE_CONTROL_POLICY" | "TAG_POLICY" | "BACKUP_POLICY" | "AISERVICES_OPT_OUT_POLICY"
object PolicyType {
  val SERVICE_CONTROL_POLICY: "SERVICE_CONTROL_POLICY" = "SERVICE_CONTROL_POLICY"
  val TAG_POLICY: "TAG_POLICY" = "TAG_POLICY"
  val BACKUP_POLICY: "BACKUP_POLICY" = "BACKUP_POLICY"
  val AISERVICES_OPT_OUT_POLICY: "AISERVICES_OPT_OUT_POLICY" = "AISERVICES_OPT_OUT_POLICY"

  @inline def values = js.Array[PolicyType](SERVICE_CONTROL_POLICY, TAG_POLICY, BACKUP_POLICY, AISERVICES_OPT_OUT_POLICY)
}

type PolicyTypeStatus = "ENABLED" | "PENDING_ENABLE" | "PENDING_DISABLE"
object PolicyTypeStatus {
  val ENABLED: "ENABLED" = "ENABLED"
  val PENDING_ENABLE: "PENDING_ENABLE" = "PENDING_ENABLE"
  val PENDING_DISABLE: "PENDING_DISABLE" = "PENDING_DISABLE"

  @inline def values = js.Array[PolicyTypeStatus](ENABLED, PENDING_ENABLE, PENDING_DISABLE)
}

type TargetType = "ACCOUNT" | "ORGANIZATIONAL_UNIT" | "ROOT"
object TargetType {
  val ACCOUNT: "ACCOUNT" = "ACCOUNT"
  val ORGANIZATIONAL_UNIT: "ORGANIZATIONAL_UNIT" = "ORGANIZATIONAL_UNIT"
  val ROOT: "ROOT" = "ROOT"

  @inline def values = js.Array[TargetType](ACCOUNT, ORGANIZATIONAL_UNIT, ROOT)
}
