name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📚 Docs'
    labels:
      - 'docs'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'internal'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
sort-by: 'title'
template: |
  ## Changes

  $CHANGES
