pull_request_rules:
  - name: Automatic merge on Scala Steward
    conditions:
      - "author=scala-steward"
      - "#status-success>=4"
    actions:
      merge:
        method: merge
      label:
        add: ["dependencies"]

  - name: Automatic merge on Dependeabot
    conditions:
      - "author~=^dependabot"
      - "#status-success>=4"
    actions:
      merge:
        method: merge
