pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=scala-steward"
      - "status-success=Travis CI - Pull Request"
      - "status-success=format"
    actions:
      merge:
        method: merge
      label:
        add: ["internal"]
