pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=scala-steward"
      - "#status-success>=4"
    actions:
      merge:
        method: merge
      label:
        add: ["internal"]
