pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=scala-steward"
      - "check-success~=CI"
      - "check-success=format"
    actions:
      merge:
        method: merge
      label:
        add: ["internal"]
