dist: xenial
language: scala

scala:
  - 2.12.9
  - 2.13.0

jdk:
  - openjdk8
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION all/test

matrix:
  include:
    - scala: 2.13.0
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
      env: JOB_NAME=FORMAT_CHECK_ONLY

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    - SCALAJS_LINK_MAX="1"
