dist: xenial
language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk11

script:
  - sbt -jvm-opts .travis/jvmopts ++$TRAVIS_SCALA_VERSION all/test;

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
    - $HOME/.sbt/boot

env:
  global:
    - SCALAJS_LINK_MAX="1"
  matrix:
    - SCALAJS_VERSION="0.6.32"
    - SCALAJS_VERSION="1.1.0"
