dist: xenial
language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk11

script:
  - sbt -jvm-opts .travis/jvmopts ++$TRAVIS_SCALA_VERSION all/test

matrix:
  include:
    - scala: 2.13.1
      script: sbt -jvm-opts .travis/jvmopts ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
      env: JOB_NAME=FORMAT_CHECK_ONLY

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
    - $HOME/.sbt/boot

env:
  global:
    - SCALAJS_LINK_MAX="1"
