package facade.amazonaws.services.migrationhub

import scalajs._

type ApplicationStatus = "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED"
object ApplicationStatus {
  val NOT_STARTED: "NOT_STARTED" = "NOT_STARTED"
  val IN_PROGRESS: "IN_PROGRESS" = "IN_PROGRESS"
  val COMPLETED: "COMPLETED" = "COMPLETED"

  @inline def values = js.Array[ApplicationStatus](NOT_STARTED, IN_PROGRESS, COMPLETED)
}

type ResourceAttributeType = "IPV4_ADDRESS" | "IPV6_ADDRESS" | "MAC_ADDRESS" | "FQDN" | "VM_MANAGER_ID" | "VM_MANAGED_OBJECT_REFERENCE" | "VM_NAME" | "VM_PATH" | "BIOS_ID" | "MOTHERBOARD_SERIAL_NUMBER"
object ResourceAttributeType {
  val IPV4_ADDRESS: "IPV4_ADDRESS" = "IPV4_ADDRESS"
  val IPV6_ADDRESS: "IPV6_ADDRESS" = "IPV6_ADDRESS"
  val MAC_ADDRESS: "MAC_ADDRESS" = "MAC_ADDRESS"
  val FQDN: "FQDN" = "FQDN"
  val VM_MANAGER_ID: "VM_MANAGER_ID" = "VM_MANAGER_ID"
  val VM_MANAGED_OBJECT_REFERENCE: "VM_MANAGED_OBJECT_REFERENCE" = "VM_MANAGED_OBJECT_REFERENCE"
  val VM_NAME: "VM_NAME" = "VM_NAME"
  val VM_PATH: "VM_PATH" = "VM_PATH"
  val BIOS_ID: "BIOS_ID" = "BIOS_ID"
  val MOTHERBOARD_SERIAL_NUMBER: "MOTHERBOARD_SERIAL_NUMBER" = "MOTHERBOARD_SERIAL_NUMBER"

  @inline def values = js.Array[ResourceAttributeType](IPV4_ADDRESS, IPV6_ADDRESS, MAC_ADDRESS, FQDN, VM_MANAGER_ID, VM_MANAGED_OBJECT_REFERENCE, VM_NAME, VM_PATH, BIOS_ID, MOTHERBOARD_SERIAL_NUMBER)
}

type Status = "NOT_STARTED" | "IN_PROGRESS" | "FAILED" | "COMPLETED"
object Status {
  val NOT_STARTED: "NOT_STARTED" = "NOT_STARTED"
  val IN_PROGRESS: "IN_PROGRESS" = "IN_PROGRESS"
  val FAILED: "FAILED" = "FAILED"
  val COMPLETED: "COMPLETED" = "COMPLETED"

  @inline def values = js.Array[Status](NOT_STARTED, IN_PROGRESS, FAILED, COMPLETED)
}
