package facade.amazonaws.services.appconfig

import scalajs._

type DeploymentEventType = "PERCENTAGE_UPDATED" | "ROLLBACK_STARTED" | "ROLLBACK_COMPLETED" | "BAKE_TIME_STARTED" | "DEPLOYMENT_STARTED" | "DEPLOYMENT_COMPLETED"
object DeploymentEventType {
  val PERCENTAGE_UPDATED: "PERCENTAGE_UPDATED" = "PERCENTAGE_UPDATED"
  val ROLLBACK_STARTED: "ROLLBACK_STARTED" = "ROLLBACK_STARTED"
  val ROLLBACK_COMPLETED: "ROLLBACK_COMPLETED" = "ROLLBACK_COMPLETED"
  val BAKE_TIME_STARTED: "BAKE_TIME_STARTED" = "BAKE_TIME_STARTED"
  val DEPLOYMENT_STARTED: "DEPLOYMENT_STARTED" = "DEPLOYMENT_STARTED"
  val DEPLOYMENT_COMPLETED: "DEPLOYMENT_COMPLETED" = "DEPLOYMENT_COMPLETED"

  @inline def values = js.Array[DeploymentEventType](PERCENTAGE_UPDATED, ROLLBACK_STARTED, ROLLBACK_COMPLETED, BAKE_TIME_STARTED, DEPLOYMENT_STARTED, DEPLOYMENT_COMPLETED)
}

type DeploymentState = "BAKING" | "VALIDATING" | "DEPLOYING" | "COMPLETE" | "ROLLING_BACK" | "ROLLED_BACK"
object DeploymentState {
  val BAKING: "BAKING" = "BAKING"
  val VALIDATING: "VALIDATING" = "VALIDATING"
  val DEPLOYING: "DEPLOYING" = "DEPLOYING"
  val COMPLETE: "COMPLETE" = "COMPLETE"
  val ROLLING_BACK: "ROLLING_BACK" = "ROLLING_BACK"
  val ROLLED_BACK: "ROLLED_BACK" = "ROLLED_BACK"

  @inline def values = js.Array[DeploymentState](BAKING, VALIDATING, DEPLOYING, COMPLETE, ROLLING_BACK, ROLLED_BACK)
}

type EnvironmentState = "READY_FOR_DEPLOYMENT" | "DEPLOYING" | "ROLLING_BACK" | "ROLLED_BACK"
object EnvironmentState {
  val READY_FOR_DEPLOYMENT: "READY_FOR_DEPLOYMENT" = "READY_FOR_DEPLOYMENT"
  val DEPLOYING: "DEPLOYING" = "DEPLOYING"
  val ROLLING_BACK: "ROLLING_BACK" = "ROLLING_BACK"
  val ROLLED_BACK: "ROLLED_BACK" = "ROLLED_BACK"

  @inline def values = js.Array[EnvironmentState](READY_FOR_DEPLOYMENT, DEPLOYING, ROLLING_BACK, ROLLED_BACK)
}

type GrowthType = "LINEAR" | "EXPONENTIAL"
object GrowthType {
  val LINEAR: "LINEAR" = "LINEAR"
  val EXPONENTIAL: "EXPONENTIAL" = "EXPONENTIAL"

  @inline def values = js.Array[GrowthType](LINEAR, EXPONENTIAL)
}

type ReplicateTo = "NONE" | "SSM_DOCUMENT"
object ReplicateTo {
  val NONE: "NONE" = "NONE"
  val SSM_DOCUMENT: "SSM_DOCUMENT" = "SSM_DOCUMENT"

  @inline def values = js.Array[ReplicateTo](NONE, SSM_DOCUMENT)
}

type TriggeredBy = "USER" | "APPCONFIG" | "CLOUDWATCH_ALARM" | "INTERNAL_ERROR"
object TriggeredBy {
  val USER: "USER" = "USER"
  val APPCONFIG: "APPCONFIG" = "APPCONFIG"
  val CLOUDWATCH_ALARM: "CLOUDWATCH_ALARM" = "CLOUDWATCH_ALARM"
  val INTERNAL_ERROR: "INTERNAL_ERROR" = "INTERNAL_ERROR"

  @inline def values = js.Array[TriggeredBy](USER, APPCONFIG, CLOUDWATCH_ALARM, INTERNAL_ERROR)
}

type ValidatorType = "JSON_SCHEMA" | "LAMBDA"
object ValidatorType {
  val JSON_SCHEMA: "JSON_SCHEMA" = "JSON_SCHEMA"
  val LAMBDA: "LAMBDA" = "LAMBDA"

  @inline def values = js.Array[ValidatorType](JSON_SCHEMA, LAMBDA)
}
