package facade.amazonaws.services.acmpca

import scalajs._

type AccessMethodType = "CA_REPOSITORY" | "RESOURCE_PKI_MANIFEST" | "RESOURCE_PKI_NOTIFY"
object AccessMethodType {
  val CA_REPOSITORY: "CA_REPOSITORY" = "CA_REPOSITORY"
  val RESOURCE_PKI_MANIFEST: "RESOURCE_PKI_MANIFEST" = "RESOURCE_PKI_MANIFEST"
  val RESOURCE_PKI_NOTIFY: "RESOURCE_PKI_NOTIFY" = "RESOURCE_PKI_NOTIFY"

  @inline def values = js.Array[AccessMethodType](CA_REPOSITORY, RESOURCE_PKI_MANIFEST, RESOURCE_PKI_NOTIFY)
}

type ActionType = "IssueCertificate" | "GetCertificate" | "ListPermissions"
object ActionType {
  val IssueCertificate: "IssueCertificate" = "IssueCertificate"
  val GetCertificate: "GetCertificate" = "GetCertificate"
  val ListPermissions: "ListPermissions" = "ListPermissions"

  @inline def values = js.Array[ActionType](IssueCertificate, GetCertificate, ListPermissions)
}

type AuditReportResponseFormat = "JSON" | "CSV"
object AuditReportResponseFormat {
  val JSON: "JSON" = "JSON"
  val CSV: "CSV" = "CSV"

  @inline def values = js.Array[AuditReportResponseFormat](JSON, CSV)
}

type AuditReportStatus = "CREATING" | "SUCCESS" | "FAILED"
object AuditReportStatus {
  val CREATING: "CREATING" = "CREATING"
  val SUCCESS: "SUCCESS" = "SUCCESS"
  val FAILED: "FAILED" = "FAILED"

  @inline def values = js.Array[AuditReportStatus](CREATING, SUCCESS, FAILED)
}

type CertificateAuthorityStatus = "CREATING" | "PENDING_CERTIFICATE" | "ACTIVE" | "DELETED" | "DISABLED" | "EXPIRED" | "FAILED"
object CertificateAuthorityStatus {
  val CREATING: "CREATING" = "CREATING"
  val PENDING_CERTIFICATE: "PENDING_CERTIFICATE" = "PENDING_CERTIFICATE"
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val DELETED: "DELETED" = "DELETED"
  val DISABLED: "DISABLED" = "DISABLED"
  val EXPIRED: "EXPIRED" = "EXPIRED"
  val FAILED: "FAILED" = "FAILED"

  @inline def values = js.Array[CertificateAuthorityStatus](CREATING, PENDING_CERTIFICATE, ACTIVE, DELETED, DISABLED, EXPIRED, FAILED)
}

type CertificateAuthorityType = "ROOT" | "SUBORDINATE"
object CertificateAuthorityType {
  val ROOT: "ROOT" = "ROOT"
  val SUBORDINATE: "SUBORDINATE" = "SUBORDINATE"

  @inline def values = js.Array[CertificateAuthorityType](ROOT, SUBORDINATE)
}

type ExtendedKeyUsageType = "SERVER_AUTH" | "CLIENT_AUTH" | "CODE_SIGNING" | "EMAIL_PROTECTION" | "TIME_STAMPING" | "OCSP_SIGNING" | "SMART_CARD_LOGIN" | "DOCUMENT_SIGNING" | "CERTIFICATE_TRANSPARENCY"
object ExtendedKeyUsageType {
  val SERVER_AUTH: "SERVER_AUTH" = "SERVER_AUTH"
  val CLIENT_AUTH: "CLIENT_AUTH" = "CLIENT_AUTH"
  val CODE_SIGNING: "CODE_SIGNING" = "CODE_SIGNING"
  val EMAIL_PROTECTION: "EMAIL_PROTECTION" = "EMAIL_PROTECTION"
  val TIME_STAMPING: "TIME_STAMPING" = "TIME_STAMPING"
  val OCSP_SIGNING: "OCSP_SIGNING" = "OCSP_SIGNING"
  val SMART_CARD_LOGIN: "SMART_CARD_LOGIN" = "SMART_CARD_LOGIN"
  val DOCUMENT_SIGNING: "DOCUMENT_SIGNING" = "DOCUMENT_SIGNING"
  val CERTIFICATE_TRANSPARENCY: "CERTIFICATE_TRANSPARENCY" = "CERTIFICATE_TRANSPARENCY"

  @inline def values = js.Array[ExtendedKeyUsageType](SERVER_AUTH, CLIENT_AUTH, CODE_SIGNING, EMAIL_PROTECTION, TIME_STAMPING, OCSP_SIGNING, SMART_CARD_LOGIN, DOCUMENT_SIGNING, CERTIFICATE_TRANSPARENCY)
}

type FailureReason = "REQUEST_TIMED_OUT" | "UNSUPPORTED_ALGORITHM" | "OTHER"
object FailureReason {
  val REQUEST_TIMED_OUT: "REQUEST_TIMED_OUT" = "REQUEST_TIMED_OUT"
  val UNSUPPORTED_ALGORITHM: "UNSUPPORTED_ALGORITHM" = "UNSUPPORTED_ALGORITHM"
  val OTHER: "OTHER" = "OTHER"

  @inline def values = js.Array[FailureReason](REQUEST_TIMED_OUT, UNSUPPORTED_ALGORITHM, OTHER)
}

type KeyAlgorithm = "RSA_2048" | "RSA_4096" | "EC_prime256v1" | "EC_secp384r1"
object KeyAlgorithm {
  val RSA_2048: "RSA_2048" = "RSA_2048"
  val RSA_4096: "RSA_4096" = "RSA_4096"
  val EC_prime256v1: "EC_prime256v1" = "EC_prime256v1"
  val EC_secp384r1: "EC_secp384r1" = "EC_secp384r1"

  @inline def values = js.Array[KeyAlgorithm](RSA_2048, RSA_4096, EC_prime256v1, EC_secp384r1)
}

type PolicyQualifierId = "CPS"
object PolicyQualifierId {
  val CPS: "CPS" = "CPS"

  @inline def values = js.Array[PolicyQualifierId](CPS)
}

type ResourceOwner = "SELF" | "OTHER_ACCOUNTS"
object ResourceOwner {
  val SELF: "SELF" = "SELF"
  val OTHER_ACCOUNTS: "OTHER_ACCOUNTS" = "OTHER_ACCOUNTS"

  @inline def values = js.Array[ResourceOwner](SELF, OTHER_ACCOUNTS)
}

type RevocationReason = "UNSPECIFIED" | "KEY_COMPROMISE" | "CERTIFICATE_AUTHORITY_COMPROMISE" | "AFFILIATION_CHANGED" | "SUPERSEDED" | "CESSATION_OF_OPERATION" | "PRIVILEGE_WITHDRAWN" | "A_A_COMPROMISE"
object RevocationReason {
  val UNSPECIFIED: "UNSPECIFIED" = "UNSPECIFIED"
  val KEY_COMPROMISE: "KEY_COMPROMISE" = "KEY_COMPROMISE"
  val CERTIFICATE_AUTHORITY_COMPROMISE: "CERTIFICATE_AUTHORITY_COMPROMISE" = "CERTIFICATE_AUTHORITY_COMPROMISE"
  val AFFILIATION_CHANGED: "AFFILIATION_CHANGED" = "AFFILIATION_CHANGED"
  val SUPERSEDED: "SUPERSEDED" = "SUPERSEDED"
  val CESSATION_OF_OPERATION: "CESSATION_OF_OPERATION" = "CESSATION_OF_OPERATION"
  val PRIVILEGE_WITHDRAWN: "PRIVILEGE_WITHDRAWN" = "PRIVILEGE_WITHDRAWN"
  val A_A_COMPROMISE: "A_A_COMPROMISE" = "A_A_COMPROMISE"

  @inline def values = js.Array[RevocationReason](UNSPECIFIED, KEY_COMPROMISE, CERTIFICATE_AUTHORITY_COMPROMISE, AFFILIATION_CHANGED, SUPERSEDED, CESSATION_OF_OPERATION, PRIVILEGE_WITHDRAWN, A_A_COMPROMISE)
}

type SigningAlgorithm = "SHA256WITHECDSA" | "SHA384WITHECDSA" | "SHA512WITHECDSA" | "SHA256WITHRSA" | "SHA384WITHRSA" | "SHA512WITHRSA"
object SigningAlgorithm {
  val SHA256WITHECDSA: "SHA256WITHECDSA" = "SHA256WITHECDSA"
  val SHA384WITHECDSA: "SHA384WITHECDSA" = "SHA384WITHECDSA"
  val SHA512WITHECDSA: "SHA512WITHECDSA" = "SHA512WITHECDSA"
  val SHA256WITHRSA: "SHA256WITHRSA" = "SHA256WITHRSA"
  val SHA384WITHRSA: "SHA384WITHRSA" = "SHA384WITHRSA"
  val SHA512WITHRSA: "SHA512WITHRSA" = "SHA512WITHRSA"

  @inline def values = js.Array[SigningAlgorithm](SHA256WITHECDSA, SHA384WITHECDSA, SHA512WITHECDSA, SHA256WITHRSA, SHA384WITHRSA, SHA512WITHRSA)
}

type ValidityPeriodType = "END_DATE" | "ABSOLUTE" | "DAYS" | "MONTHS" | "YEARS"
object ValidityPeriodType {
  val END_DATE: "END_DATE" = "END_DATE"
  val ABSOLUTE: "ABSOLUTE" = "ABSOLUTE"
  val DAYS: "DAYS" = "DAYS"
  val MONTHS: "MONTHS" = "MONTHS"
  val YEARS: "YEARS" = "YEARS"

  @inline def values = js.Array[ValidityPeriodType](END_DATE, ABSOLUTE, DAYS, MONTHS, YEARS)
}
