package facade.amazonaws.services.acm

import scalajs.js

type CertificateStatus = "PENDING_VALIDATION" | "ISSUED" | "INACTIVE" | "EXPIRED" | "VALIDATION_TIMED_OUT" | "REVOKED" | "FAILED"
object CertificateStatus {
  inline val PENDING_VALIDATION: "PENDING_VALIDATION" = "PENDING_VALIDATION"
  inline val ISSUED: "ISSUED" = "ISSUED"
  inline val INACTIVE: "INACTIVE" = "INACTIVE"
  inline val EXPIRED: "EXPIRED" = "EXPIRED"
  inline val VALIDATION_TIMED_OUT: "VALIDATION_TIMED_OUT" = "VALIDATION_TIMED_OUT"
  inline val REVOKED: "REVOKED" = "REVOKED"
  inline val FAILED: "FAILED" = "FAILED"

  inline def values: js.Array[CertificateStatus] = js.Array(PENDING_VALIDATION, ISSUED, INACTIVE, EXPIRED, VALIDATION_TIMED_OUT, REVOKED, FAILED)
}

type CertificateTransparencyLoggingPreference = "ENABLED" | "DISABLED"
object CertificateTransparencyLoggingPreference {
  inline val ENABLED: "ENABLED" = "ENABLED"
  inline val DISABLED: "DISABLED" = "DISABLED"

  inline def values: js.Array[CertificateTransparencyLoggingPreference] = js.Array(ENABLED, DISABLED)
}

type CertificateType = "IMPORTED" | "AMAZON_ISSUED" | "PRIVATE"
object CertificateType {
  inline val IMPORTED: "IMPORTED" = "IMPORTED"
  inline val AMAZON_ISSUED: "AMAZON_ISSUED" = "AMAZON_ISSUED"
  inline val PRIVATE: "PRIVATE" = "PRIVATE"

  inline def values: js.Array[CertificateType] = js.Array(IMPORTED, AMAZON_ISSUED, PRIVATE)
}

type DomainStatus = "PENDING_VALIDATION" | "SUCCESS" | "FAILED"
object DomainStatus {
  inline val PENDING_VALIDATION: "PENDING_VALIDATION" = "PENDING_VALIDATION"
  inline val SUCCESS: "SUCCESS" = "SUCCESS"
  inline val FAILED: "FAILED" = "FAILED"

  inline def values: js.Array[DomainStatus] = js.Array(PENDING_VALIDATION, SUCCESS, FAILED)
}

type ExtendedKeyUsageName = "TLS_WEB_SERVER_AUTHENTICATION" | "TLS_WEB_CLIENT_AUTHENTICATION" | "CODE_SIGNING" | "EMAIL_PROTECTION" | "TIME_STAMPING" | "OCSP_SIGNING" | "IPSEC_END_SYSTEM" | "IPSEC_TUNNEL" | "IPSEC_USER" | "ANY" | "NONE" | "CUSTOM"
object ExtendedKeyUsageName {
  inline val TLS_WEB_SERVER_AUTHENTICATION: "TLS_WEB_SERVER_AUTHENTICATION" = "TLS_WEB_SERVER_AUTHENTICATION"
  inline val TLS_WEB_CLIENT_AUTHENTICATION: "TLS_WEB_CLIENT_AUTHENTICATION" = "TLS_WEB_CLIENT_AUTHENTICATION"
  inline val CODE_SIGNING: "CODE_SIGNING" = "CODE_SIGNING"
  inline val EMAIL_PROTECTION: "EMAIL_PROTECTION" = "EMAIL_PROTECTION"
  inline val TIME_STAMPING: "TIME_STAMPING" = "TIME_STAMPING"
  inline val OCSP_SIGNING: "OCSP_SIGNING" = "OCSP_SIGNING"
  inline val IPSEC_END_SYSTEM: "IPSEC_END_SYSTEM" = "IPSEC_END_SYSTEM"
  inline val IPSEC_TUNNEL: "IPSEC_TUNNEL" = "IPSEC_TUNNEL"
  inline val IPSEC_USER: "IPSEC_USER" = "IPSEC_USER"
  inline val ANY: "ANY" = "ANY"
  inline val NONE: "NONE" = "NONE"
  inline val CUSTOM: "CUSTOM" = "CUSTOM"

  inline def values: js.Array[ExtendedKeyUsageName] = js.Array(
    TLS_WEB_SERVER_AUTHENTICATION,
    TLS_WEB_CLIENT_AUTHENTICATION,
    CODE_SIGNING,
    EMAIL_PROTECTION,
    TIME_STAMPING,
    OCSP_SIGNING,
    IPSEC_END_SYSTEM,
    IPSEC_TUNNEL,
    IPSEC_USER,
    ANY,
    NONE,
    CUSTOM
  )
}

type FailureReason = "NO_AVAILABLE_CONTACTS" | "ADDITIONAL_VERIFICATION_REQUIRED" | "DOMAIN_NOT_ALLOWED" | "INVALID_PUBLIC_DOMAIN" | "DOMAIN_VALIDATION_DENIED" | "CAA_ERROR" | "PCA_LIMIT_EXCEEDED" | "PCA_INVALID_ARN" | "PCA_INVALID_STATE" | "PCA_REQUEST_FAILED" | "PCA_NAME_CONSTRAINTS_VALIDATION" | "PCA_RESOURCE_NOT_FOUND" | "PCA_INVALID_ARGS" | "PCA_INVALID_DURATION" | "PCA_ACCESS_DENIED" | "SLR_NOT_FOUND" | "OTHER"
object FailureReason {
  inline val NO_AVAILABLE_CONTACTS: "NO_AVAILABLE_CONTACTS" = "NO_AVAILABLE_CONTACTS"
  inline val ADDITIONAL_VERIFICATION_REQUIRED: "ADDITIONAL_VERIFICATION_REQUIRED" = "ADDITIONAL_VERIFICATION_REQUIRED"
  inline val DOMAIN_NOT_ALLOWED: "DOMAIN_NOT_ALLOWED" = "DOMAIN_NOT_ALLOWED"
  inline val INVALID_PUBLIC_DOMAIN: "INVALID_PUBLIC_DOMAIN" = "INVALID_PUBLIC_DOMAIN"
  inline val DOMAIN_VALIDATION_DENIED: "DOMAIN_VALIDATION_DENIED" = "DOMAIN_VALIDATION_DENIED"
  inline val CAA_ERROR: "CAA_ERROR" = "CAA_ERROR"
  inline val PCA_LIMIT_EXCEEDED: "PCA_LIMIT_EXCEEDED" = "PCA_LIMIT_EXCEEDED"
  inline val PCA_INVALID_ARN: "PCA_INVALID_ARN" = "PCA_INVALID_ARN"
  inline val PCA_INVALID_STATE: "PCA_INVALID_STATE" = "PCA_INVALID_STATE"
  inline val PCA_REQUEST_FAILED: "PCA_REQUEST_FAILED" = "PCA_REQUEST_FAILED"
  inline val PCA_NAME_CONSTRAINTS_VALIDATION: "PCA_NAME_CONSTRAINTS_VALIDATION" = "PCA_NAME_CONSTRAINTS_VALIDATION"
  inline val PCA_RESOURCE_NOT_FOUND: "PCA_RESOURCE_NOT_FOUND" = "PCA_RESOURCE_NOT_FOUND"
  inline val PCA_INVALID_ARGS: "PCA_INVALID_ARGS" = "PCA_INVALID_ARGS"
  inline val PCA_INVALID_DURATION: "PCA_INVALID_DURATION" = "PCA_INVALID_DURATION"
  inline val PCA_ACCESS_DENIED: "PCA_ACCESS_DENIED" = "PCA_ACCESS_DENIED"
  inline val SLR_NOT_FOUND: "SLR_NOT_FOUND" = "SLR_NOT_FOUND"
  inline val OTHER: "OTHER" = "OTHER"

  inline def values: js.Array[FailureReason] = js.Array(
    NO_AVAILABLE_CONTACTS,
    ADDITIONAL_VERIFICATION_REQUIRED,
    DOMAIN_NOT_ALLOWED,
    INVALID_PUBLIC_DOMAIN,
    DOMAIN_VALIDATION_DENIED,
    CAA_ERROR,
    PCA_LIMIT_EXCEEDED,
    PCA_INVALID_ARN,
    PCA_INVALID_STATE,
    PCA_REQUEST_FAILED,
    PCA_NAME_CONSTRAINTS_VALIDATION,
    PCA_RESOURCE_NOT_FOUND,
    PCA_INVALID_ARGS,
    PCA_INVALID_DURATION,
    PCA_ACCESS_DENIED,
    SLR_NOT_FOUND,
    OTHER
  )
}

type KeyAlgorithm = "RSA_2048" | "RSA_1024" | "RSA_4096" | "EC_prime256v1" | "EC_secp384r1" | "EC_secp521r1"
object KeyAlgorithm {
  inline val RSA_2048: "RSA_2048" = "RSA_2048"
  inline val RSA_1024: "RSA_1024" = "RSA_1024"
  inline val RSA_4096: "RSA_4096" = "RSA_4096"
  inline val EC_prime256v1: "EC_prime256v1" = "EC_prime256v1"
  inline val EC_secp384r1: "EC_secp384r1" = "EC_secp384r1"
  inline val EC_secp521r1: "EC_secp521r1" = "EC_secp521r1"

  inline def values: js.Array[KeyAlgorithm] = js.Array(RSA_2048, RSA_1024, RSA_4096, EC_prime256v1, EC_secp384r1, EC_secp521r1)
}

type KeyUsageName = "DIGITAL_SIGNATURE" | "NON_REPUDIATION" | "KEY_ENCIPHERMENT" | "DATA_ENCIPHERMENT" | "KEY_AGREEMENT" | "CERTIFICATE_SIGNING" | "CRL_SIGNING" | "ENCIPHER_ONLY" | "DECIPHER_ONLY" | "ANY" | "CUSTOM"
object KeyUsageName {
  inline val DIGITAL_SIGNATURE: "DIGITAL_SIGNATURE" = "DIGITAL_SIGNATURE"
  inline val NON_REPUDIATION: "NON_REPUDIATION" = "NON_REPUDIATION"
  inline val KEY_ENCIPHERMENT: "KEY_ENCIPHERMENT" = "KEY_ENCIPHERMENT"
  inline val DATA_ENCIPHERMENT: "DATA_ENCIPHERMENT" = "DATA_ENCIPHERMENT"
  inline val KEY_AGREEMENT: "KEY_AGREEMENT" = "KEY_AGREEMENT"
  inline val CERTIFICATE_SIGNING: "CERTIFICATE_SIGNING" = "CERTIFICATE_SIGNING"
  inline val CRL_SIGNING: "CRL_SIGNING" = "CRL_SIGNING"
  inline val ENCIPHER_ONLY: "ENCIPHER_ONLY" = "ENCIPHER_ONLY"
  inline val DECIPHER_ONLY: "DECIPHER_ONLY" = "DECIPHER_ONLY"
  inline val ANY: "ANY" = "ANY"
  inline val CUSTOM: "CUSTOM" = "CUSTOM"

  inline def values: js.Array[KeyUsageName] = js.Array(
    DIGITAL_SIGNATURE,
    NON_REPUDIATION,
    KEY_ENCIPHERMENT,
    DATA_ENCIPHERMENT,
    KEY_AGREEMENT,
    CERTIFICATE_SIGNING,
    CRL_SIGNING,
    ENCIPHER_ONLY,
    DECIPHER_ONLY,
    ANY,
    CUSTOM
  )
}

type RecordType = "CNAME"
object RecordType {
  inline val CNAME: "CNAME" = "CNAME"

  inline def values: js.Array[RecordType] = js.Array(CNAME)
}

type RenewalEligibility = "ELIGIBLE" | "INELIGIBLE"
object RenewalEligibility {
  inline val ELIGIBLE: "ELIGIBLE" = "ELIGIBLE"
  inline val INELIGIBLE: "INELIGIBLE" = "INELIGIBLE"

  inline def values: js.Array[RenewalEligibility] = js.Array(ELIGIBLE, INELIGIBLE)
}

type RenewalStatus = "PENDING_AUTO_RENEWAL" | "PENDING_VALIDATION" | "SUCCESS" | "FAILED"
object RenewalStatus {
  inline val PENDING_AUTO_RENEWAL: "PENDING_AUTO_RENEWAL" = "PENDING_AUTO_RENEWAL"
  inline val PENDING_VALIDATION: "PENDING_VALIDATION" = "PENDING_VALIDATION"
  inline val SUCCESS: "SUCCESS" = "SUCCESS"
  inline val FAILED: "FAILED" = "FAILED"

  inline def values: js.Array[RenewalStatus] = js.Array(PENDING_AUTO_RENEWAL, PENDING_VALIDATION, SUCCESS, FAILED)
}

type RevocationReason = "UNSPECIFIED" | "KEY_COMPROMISE" | "CA_COMPROMISE" | "AFFILIATION_CHANGED" | "SUPERCEDED" | "CESSATION_OF_OPERATION" | "CERTIFICATE_HOLD" | "REMOVE_FROM_CRL" | "PRIVILEGE_WITHDRAWN" | "A_A_COMPROMISE"
object RevocationReason {
  inline val UNSPECIFIED: "UNSPECIFIED" = "UNSPECIFIED"
  inline val KEY_COMPROMISE: "KEY_COMPROMISE" = "KEY_COMPROMISE"
  inline val CA_COMPROMISE: "CA_COMPROMISE" = "CA_COMPROMISE"
  inline val AFFILIATION_CHANGED: "AFFILIATION_CHANGED" = "AFFILIATION_CHANGED"
  inline val SUPERCEDED: "SUPERCEDED" = "SUPERCEDED"
  inline val CESSATION_OF_OPERATION: "CESSATION_OF_OPERATION" = "CESSATION_OF_OPERATION"
  inline val CERTIFICATE_HOLD: "CERTIFICATE_HOLD" = "CERTIFICATE_HOLD"
  inline val REMOVE_FROM_CRL: "REMOVE_FROM_CRL" = "REMOVE_FROM_CRL"
  inline val PRIVILEGE_WITHDRAWN: "PRIVILEGE_WITHDRAWN" = "PRIVILEGE_WITHDRAWN"
  inline val A_A_COMPROMISE: "A_A_COMPROMISE" = "A_A_COMPROMISE"

  inline def values: js.Array[RevocationReason] = js.Array(
    UNSPECIFIED,
    KEY_COMPROMISE,
    CA_COMPROMISE,
    AFFILIATION_CHANGED,
    SUPERCEDED,
    CESSATION_OF_OPERATION,
    CERTIFICATE_HOLD,
    REMOVE_FROM_CRL,
    PRIVILEGE_WITHDRAWN,
    A_A_COMPROMISE
  )
}

type ValidationMethod = "EMAIL" | "DNS"
object ValidationMethod {
  inline val EMAIL: "EMAIL" = "EMAIL"
  inline val DNS: "DNS" = "DNS"

  inline def values: js.Array[ValidationMethod] = js.Array(EMAIL, DNS)
}
