package facade.amazonaws.services.applicationdiscovery

import scalajs._

type AgentStatus = "HEALTHY" | "UNHEALTHY" | "RUNNING" | "UNKNOWN" | "BLACKLISTED" | "SHUTDOWN"
object AgentStatus {
  val HEALTHY: "HEALTHY" = "HEALTHY"
  val UNHEALTHY: "UNHEALTHY" = "UNHEALTHY"
  val RUNNING: "RUNNING" = "RUNNING"
  val UNKNOWN: "UNKNOWN" = "UNKNOWN"
  val BLACKLISTED: "BLACKLISTED" = "BLACKLISTED"
  val SHUTDOWN: "SHUTDOWN" = "SHUTDOWN"

  @inline def values = js.Array[AgentStatus](HEALTHY, UNHEALTHY, RUNNING, UNKNOWN, BLACKLISTED, SHUTDOWN)
}

type BatchDeleteImportDataErrorCode = "NOT_FOUND" | "INTERNAL_SERVER_ERROR" | "OVER_LIMIT"
object BatchDeleteImportDataErrorCode {
  val NOT_FOUND: "NOT_FOUND" = "NOT_FOUND"
  val INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR" = "INTERNAL_SERVER_ERROR"
  val OVER_LIMIT: "OVER_LIMIT" = "OVER_LIMIT"

  @inline def values = js.Array[BatchDeleteImportDataErrorCode](NOT_FOUND, INTERNAL_SERVER_ERROR, OVER_LIMIT)
}

type ConfigurationItemType = "SERVER" | "PROCESS" | "CONNECTION" | "APPLICATION"
object ConfigurationItemType {
  val SERVER: "SERVER" = "SERVER"
  val PROCESS: "PROCESS" = "PROCESS"
  val CONNECTION: "CONNECTION" = "CONNECTION"
  val APPLICATION: "APPLICATION" = "APPLICATION"

  @inline def values = js.Array[ConfigurationItemType](SERVER, PROCESS, CONNECTION, APPLICATION)
}

type ContinuousExportStatus = "START_IN_PROGRESS" | "START_FAILED" | "ACTIVE" | "ERROR" | "STOP_IN_PROGRESS" | "STOP_FAILED" | "INACTIVE"
object ContinuousExportStatus {
  val START_IN_PROGRESS: "START_IN_PROGRESS" = "START_IN_PROGRESS"
  val START_FAILED: "START_FAILED" = "START_FAILED"
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val ERROR: "ERROR" = "ERROR"
  val STOP_IN_PROGRESS: "STOP_IN_PROGRESS" = "STOP_IN_PROGRESS"
  val STOP_FAILED: "STOP_FAILED" = "STOP_FAILED"
  val INACTIVE: "INACTIVE" = "INACTIVE"

  @inline def values = js.Array[ContinuousExportStatus](START_IN_PROGRESS, START_FAILED, ACTIVE, ERROR, STOP_IN_PROGRESS, STOP_FAILED, INACTIVE)
}

type DataSource = "AGENT"
object DataSource {
  val AGENT: "AGENT" = "AGENT"

  @inline def values = js.Array[DataSource](AGENT)
}

type ExportDataFormat = "CSV" | "GRAPHML"
object ExportDataFormat {
  val CSV: "CSV" = "CSV"
  val GRAPHML: "GRAPHML" = "GRAPHML"

  @inline def values = js.Array[ExportDataFormat](CSV, GRAPHML)
}

type ExportStatus = "FAILED" | "SUCCEEDED" | "IN_PROGRESS"
object ExportStatus {
  val FAILED: "FAILED" = "FAILED"
  val SUCCEEDED: "SUCCEEDED" = "SUCCEEDED"
  val IN_PROGRESS: "IN_PROGRESS" = "IN_PROGRESS"

  @inline def values = js.Array[ExportStatus](FAILED, SUCCEEDED, IN_PROGRESS)
}

type ImportStatus = "IMPORT_IN_PROGRESS" | "IMPORT_COMPLETE" | "IMPORT_COMPLETE_WITH_ERRORS" | "IMPORT_FAILED" | "IMPORT_FAILED_SERVER_LIMIT_EXCEEDED" | "IMPORT_FAILED_RECORD_LIMIT_EXCEEDED" | "DELETE_IN_PROGRESS" | "DELETE_COMPLETE" | "DELETE_FAILED" | "DELETE_FAILED_LIMIT_EXCEEDED" | "INTERNAL_ERROR"
object ImportStatus {
  val IMPORT_IN_PROGRESS: "IMPORT_IN_PROGRESS" = "IMPORT_IN_PROGRESS"
  val IMPORT_COMPLETE: "IMPORT_COMPLETE" = "IMPORT_COMPLETE"
  val IMPORT_COMPLETE_WITH_ERRORS: "IMPORT_COMPLETE_WITH_ERRORS" = "IMPORT_COMPLETE_WITH_ERRORS"
  val IMPORT_FAILED: "IMPORT_FAILED" = "IMPORT_FAILED"
  val IMPORT_FAILED_SERVER_LIMIT_EXCEEDED: "IMPORT_FAILED_SERVER_LIMIT_EXCEEDED" = "IMPORT_FAILED_SERVER_LIMIT_EXCEEDED"
  val IMPORT_FAILED_RECORD_LIMIT_EXCEEDED: "IMPORT_FAILED_RECORD_LIMIT_EXCEEDED" = "IMPORT_FAILED_RECORD_LIMIT_EXCEEDED"
  val DELETE_IN_PROGRESS: "DELETE_IN_PROGRESS" = "DELETE_IN_PROGRESS"
  val DELETE_COMPLETE: "DELETE_COMPLETE" = "DELETE_COMPLETE"
  val DELETE_FAILED: "DELETE_FAILED" = "DELETE_FAILED"
  val DELETE_FAILED_LIMIT_EXCEEDED: "DELETE_FAILED_LIMIT_EXCEEDED" = "DELETE_FAILED_LIMIT_EXCEEDED"
  val INTERNAL_ERROR: "INTERNAL_ERROR" = "INTERNAL_ERROR"

  @inline def values = js.Array[ImportStatus](
    IMPORT_IN_PROGRESS,
    IMPORT_COMPLETE,
    IMPORT_COMPLETE_WITH_ERRORS,
    IMPORT_FAILED,
    IMPORT_FAILED_SERVER_LIMIT_EXCEEDED,
    IMPORT_FAILED_RECORD_LIMIT_EXCEEDED,
    DELETE_IN_PROGRESS,
    DELETE_COMPLETE,
    DELETE_FAILED,
    DELETE_FAILED_LIMIT_EXCEEDED,
    INTERNAL_ERROR
  )
}

type ImportTaskFilterName = "IMPORT_TASK_ID" | "STATUS" | "NAME"
object ImportTaskFilterName {
  val IMPORT_TASK_ID: "IMPORT_TASK_ID" = "IMPORT_TASK_ID"
  val STATUS: "STATUS" = "STATUS"
  val NAME: "NAME" = "NAME"

  @inline def values = js.Array[ImportTaskFilterName](IMPORT_TASK_ID, STATUS, NAME)
}

type orderString = "ASC" | "DESC"
object orderString {
  val ASC: "ASC" = "ASC"
  val DESC: "DESC" = "DESC"

  @inline def values = js.Array[orderString](ASC, DESC)
}
