package facade.amazonaws.services.kinesisvideomedia

import scalajs._

type StartSelectorType = "FRAGMENT_NUMBER" | "SERVER_TIMESTAMP" | "PRODUCER_TIMESTAMP" | "NOW" | "EARLIEST" | "CONTINUATION_TOKEN"
object StartSelectorType {
  val FRAGMENT_NUMBER: "FRAGMENT_NUMBER" = "FRAGMENT_NUMBER"
  val SERVER_TIMESTAMP: "SERVER_TIMESTAMP" = "SERVER_TIMESTAMP"
  val PRODUCER_TIMESTAMP: "PRODUCER_TIMESTAMP" = "PRODUCER_TIMESTAMP"
  val NOW: "NOW" = "NOW"
  val EARLIEST: "EARLIEST" = "EARLIEST"
  val CONTINUATION_TOKEN: "CONTINUATION_TOKEN" = "CONTINUATION_TOKEN"

  @inline def values = js.Array[StartSelectorType](FRAGMENT_NUMBER, SERVER_TIMESTAMP, PRODUCER_TIMESTAMP, NOW, EARLIEST, CONTINUATION_TOKEN)
}
