package facade.amazonaws.services.kinesisvideomedia

import scalajs._

type StartSelectorType = "FRAGMENT_NUMBER" | "SERVER_TIMESTAMP" | "PRODUCER_TIMESTAMP" | "NOW" | "EARLIEST" | "CONTINUATION_TOKEN"
object StartSelectorType {
  inline val FRAGMENT_NUMBER: "FRAGMENT_NUMBER" = "FRAGMENT_NUMBER"
  inline val SERVER_TIMESTAMP: "SERVER_TIMESTAMP" = "SERVER_TIMESTAMP"
  inline val PRODUCER_TIMESTAMP: "PRODUCER_TIMESTAMP" = "PRODUCER_TIMESTAMP"
  inline val NOW: "NOW" = "NOW"
  inline val EARLIEST: "EARLIEST" = "EARLIEST"
  inline val CONTINUATION_TOKEN: "CONTINUATION_TOKEN" = "CONTINUATION_TOKEN"

  inline def values: js.Array[StartSelectorType] = js.Array(FRAGMENT_NUMBER, SERVER_TIMESTAMP, PRODUCER_TIMESTAMP, NOW, EARLIEST, CONTINUATION_TOKEN)
}
