addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "0.6.29")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.0.7")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"        % "3.8")
addSbtPlugin("com.github.gseitz" % "sbt-release"         % "1.0.12")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"             % "2.0.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.15.0-0.6")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"        % "1.2.0")
