addSbtPlugin("org.scala-js"      % "sbt-scalajs"               % "0.6.31")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"              % "2.3.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"              % "3.8.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"               % "1.0.13")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"                   % "2.0.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler-sjs06" % "0.16.0")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"              % "1.2.0")
