package facade.amazonaws.services.workdocs

import scalajs._

type ActivityType = "DOCUMENT_CHECKED_IN" | "DOCUMENT_CHECKED_OUT" | "DOCUMENT_RENAMED" | "DOCUMENT_VERSION_UPLOADED" | "DOCUMENT_VERSION_DELETED" | "DOCUMENT_VERSION_VIEWED" | "DOCUMENT_VERSION_DOWNLOADED" | "DOCUMENT_RECYCLED" | "DOCUMENT_RESTORED" | "DOCUMENT_REVERTED" | "DOCUMENT_SHARED" | "DOCUMENT_UNSHARED" | "DOCUMENT_SHARE_PERMISSION_CHANGED" | "DOCUMENT_SHAREABLE_LINK_CREATED" | "DOCUMENT_SHAREABLE_LINK_REMOVED" | "DOCUMENT_SHAREABLE_LINK_PERMISSION_CHANGED" | "DOCUMENT_MOVED" | "DOCUMENT_COMMENT_ADDED" | "DOCUMENT_COMMENT_DELETED" | "DOCUMENT_ANNOTATION_ADDED" | "DOCUMENT_ANNOTATION_DELETED" | "FOLDER_CREATED" | "FOLDER_DELETED" | "FOLDER_RENAMED" | "FOLDER_RECYCLED" | "FOLDER_RESTORED" | "FOLDER_SHARED" | "FOLDER_UNSHARED" | "FOLDER_SHARE_PERMISSION_CHANGED" | "FOLDER_SHAREABLE_LINK_CREATED" | "FOLDER_SHAREABLE_LINK_REMOVED" | "FOLDER_SHAREABLE_LINK_PERMISSION_CHANGED" | "FOLDER_MOVED"
object ActivityType {
  val DOCUMENT_CHECKED_IN: "DOCUMENT_CHECKED_IN" = "DOCUMENT_CHECKED_IN"
  val DOCUMENT_CHECKED_OUT: "DOCUMENT_CHECKED_OUT" = "DOCUMENT_CHECKED_OUT"
  val DOCUMENT_RENAMED: "DOCUMENT_RENAMED" = "DOCUMENT_RENAMED"
  val DOCUMENT_VERSION_UPLOADED: "DOCUMENT_VERSION_UPLOADED" = "DOCUMENT_VERSION_UPLOADED"
  val DOCUMENT_VERSION_DELETED: "DOCUMENT_VERSION_DELETED" = "DOCUMENT_VERSION_DELETED"
  val DOCUMENT_VERSION_VIEWED: "DOCUMENT_VERSION_VIEWED" = "DOCUMENT_VERSION_VIEWED"
  val DOCUMENT_VERSION_DOWNLOADED: "DOCUMENT_VERSION_DOWNLOADED" = "DOCUMENT_VERSION_DOWNLOADED"
  val DOCUMENT_RECYCLED: "DOCUMENT_RECYCLED" = "DOCUMENT_RECYCLED"
  val DOCUMENT_RESTORED: "DOCUMENT_RESTORED" = "DOCUMENT_RESTORED"
  val DOCUMENT_REVERTED: "DOCUMENT_REVERTED" = "DOCUMENT_REVERTED"
  val DOCUMENT_SHARED: "DOCUMENT_SHARED" = "DOCUMENT_SHARED"
  val DOCUMENT_UNSHARED: "DOCUMENT_UNSHARED" = "DOCUMENT_UNSHARED"
  val DOCUMENT_SHARE_PERMISSION_CHANGED: "DOCUMENT_SHARE_PERMISSION_CHANGED" = "DOCUMENT_SHARE_PERMISSION_CHANGED"
  val DOCUMENT_SHAREABLE_LINK_CREATED: "DOCUMENT_SHAREABLE_LINK_CREATED" = "DOCUMENT_SHAREABLE_LINK_CREATED"
  val DOCUMENT_SHAREABLE_LINK_REMOVED: "DOCUMENT_SHAREABLE_LINK_REMOVED" = "DOCUMENT_SHAREABLE_LINK_REMOVED"
  val DOCUMENT_SHAREABLE_LINK_PERMISSION_CHANGED: "DOCUMENT_SHAREABLE_LINK_PERMISSION_CHANGED" = "DOCUMENT_SHAREABLE_LINK_PERMISSION_CHANGED"
  val DOCUMENT_MOVED: "DOCUMENT_MOVED" = "DOCUMENT_MOVED"
  val DOCUMENT_COMMENT_ADDED: "DOCUMENT_COMMENT_ADDED" = "DOCUMENT_COMMENT_ADDED"
  val DOCUMENT_COMMENT_DELETED: "DOCUMENT_COMMENT_DELETED" = "DOCUMENT_COMMENT_DELETED"
  val DOCUMENT_ANNOTATION_ADDED: "DOCUMENT_ANNOTATION_ADDED" = "DOCUMENT_ANNOTATION_ADDED"
  val DOCUMENT_ANNOTATION_DELETED: "DOCUMENT_ANNOTATION_DELETED" = "DOCUMENT_ANNOTATION_DELETED"
  val FOLDER_CREATED: "FOLDER_CREATED" = "FOLDER_CREATED"
  val FOLDER_DELETED: "FOLDER_DELETED" = "FOLDER_DELETED"
  val FOLDER_RENAMED: "FOLDER_RENAMED" = "FOLDER_RENAMED"
  val FOLDER_RECYCLED: "FOLDER_RECYCLED" = "FOLDER_RECYCLED"
  val FOLDER_RESTORED: "FOLDER_RESTORED" = "FOLDER_RESTORED"
  val FOLDER_SHARED: "FOLDER_SHARED" = "FOLDER_SHARED"
  val FOLDER_UNSHARED: "FOLDER_UNSHARED" = "FOLDER_UNSHARED"
  val FOLDER_SHARE_PERMISSION_CHANGED: "FOLDER_SHARE_PERMISSION_CHANGED" = "FOLDER_SHARE_PERMISSION_CHANGED"
  val FOLDER_SHAREABLE_LINK_CREATED: "FOLDER_SHAREABLE_LINK_CREATED" = "FOLDER_SHAREABLE_LINK_CREATED"
  val FOLDER_SHAREABLE_LINK_REMOVED: "FOLDER_SHAREABLE_LINK_REMOVED" = "FOLDER_SHAREABLE_LINK_REMOVED"
  val FOLDER_SHAREABLE_LINK_PERMISSION_CHANGED: "FOLDER_SHAREABLE_LINK_PERMISSION_CHANGED" = "FOLDER_SHAREABLE_LINK_PERMISSION_CHANGED"
  val FOLDER_MOVED: "FOLDER_MOVED" = "FOLDER_MOVED"

  @inline def values = js.Array[ActivityType](
    DOCUMENT_CHECKED_IN,
    DOCUMENT_CHECKED_OUT,
    DOCUMENT_RENAMED,
    DOCUMENT_VERSION_UPLOADED,
    DOCUMENT_VERSION_DELETED,
    DOCUMENT_VERSION_VIEWED,
    DOCUMENT_VERSION_DOWNLOADED,
    DOCUMENT_RECYCLED,
    DOCUMENT_RESTORED,
    DOCUMENT_REVERTED,
    DOCUMENT_SHARED,
    DOCUMENT_UNSHARED,
    DOCUMENT_SHARE_PERMISSION_CHANGED,
    DOCUMENT_SHAREABLE_LINK_CREATED,
    DOCUMENT_SHAREABLE_LINK_REMOVED,
    DOCUMENT_SHAREABLE_LINK_PERMISSION_CHANGED,
    DOCUMENT_MOVED,
    DOCUMENT_COMMENT_ADDED,
    DOCUMENT_COMMENT_DELETED,
    DOCUMENT_ANNOTATION_ADDED,
    DOCUMENT_ANNOTATION_DELETED,
    FOLDER_CREATED,
    FOLDER_DELETED,
    FOLDER_RENAMED,
    FOLDER_RECYCLED,
    FOLDER_RESTORED,
    FOLDER_SHARED,
    FOLDER_UNSHARED,
    FOLDER_SHARE_PERMISSION_CHANGED,
    FOLDER_SHAREABLE_LINK_CREATED,
    FOLDER_SHAREABLE_LINK_REMOVED,
    FOLDER_SHAREABLE_LINK_PERMISSION_CHANGED,
    FOLDER_MOVED
  )
}

type BooleanEnumType = "TRUE" | "FALSE"
object BooleanEnumType {
  val TRUE: "TRUE" = "TRUE"
  val FALSE: "FALSE" = "FALSE"

  @inline def values = js.Array[BooleanEnumType](TRUE, FALSE)
}

type CommentStatusType = "DRAFT" | "PUBLISHED" | "DELETED"
object CommentStatusType {
  val DRAFT: "DRAFT" = "DRAFT"
  val PUBLISHED: "PUBLISHED" = "PUBLISHED"
  val DELETED: "DELETED" = "DELETED"

  @inline def values = js.Array[CommentStatusType](DRAFT, PUBLISHED, DELETED)
}

type CommentVisibilityType = "PUBLIC" | "PRIVATE"
object CommentVisibilityType {
  val PUBLIC: "PUBLIC" = "PUBLIC"
  val PRIVATE: "PRIVATE" = "PRIVATE"

  @inline def values = js.Array[CommentVisibilityType](PUBLIC, PRIVATE)
}

type DocumentSourceType = "ORIGINAL" | "WITH_COMMENTS"
object DocumentSourceType {
  val ORIGINAL: "ORIGINAL" = "ORIGINAL"
  val WITH_COMMENTS: "WITH_COMMENTS" = "WITH_COMMENTS"

  @inline def values = js.Array[DocumentSourceType](ORIGINAL, WITH_COMMENTS)
}

type DocumentStatusType = "INITIALIZED" | "ACTIVE"
object DocumentStatusType {
  val INITIALIZED: "INITIALIZED" = "INITIALIZED"
  val ACTIVE: "ACTIVE" = "ACTIVE"

  @inline def values = js.Array[DocumentStatusType](INITIALIZED, ACTIVE)
}

type DocumentThumbnailType = "SMALL" | "SMALL_HQ" | "LARGE"
object DocumentThumbnailType {
  val SMALL: "SMALL" = "SMALL"
  val SMALL_HQ: "SMALL_HQ" = "SMALL_HQ"
  val LARGE: "LARGE" = "LARGE"

  @inline def values = js.Array[DocumentThumbnailType](SMALL, SMALL_HQ, LARGE)
}

type DocumentVersionStatus = "ACTIVE"
object DocumentVersionStatus {
  val ACTIVE: "ACTIVE" = "ACTIVE"

  @inline def values = js.Array[DocumentVersionStatus](ACTIVE)
}

type FolderContentType = "ALL" | "DOCUMENT" | "FOLDER"
object FolderContentType {
  val ALL: "ALL" = "ALL"
  val DOCUMENT: "DOCUMENT" = "DOCUMENT"
  val FOLDER: "FOLDER" = "FOLDER"

  @inline def values = js.Array[FolderContentType](ALL, DOCUMENT, FOLDER)
}

type LocaleType = "en" | "fr" | "ko" | "de" | "es" | "ja" | "ru" | "zh_CN" | "zh_TW" | "pt_BR" | "default"
object LocaleType {
  val en: "en" = "en"
  val fr: "fr" = "fr"
  val ko: "ko" = "ko"
  val de: "de" = "de"
  val es: "es" = "es"
  val ja: "ja" = "ja"
  val ru: "ru" = "ru"
  val zh_CN: "zh_CN" = "zh_CN"
  val zh_TW: "zh_TW" = "zh_TW"
  val pt_BR: "pt_BR" = "pt_BR"
  val default: "default" = "default"

  @inline def values = js.Array[LocaleType](en, fr, ko, de, es, ja, ru, zh_CN, zh_TW, pt_BR, default)
}

type OrderType = "ASCENDING" | "DESCENDING"
object OrderType {
  val ASCENDING: "ASCENDING" = "ASCENDING"
  val DESCENDING: "DESCENDING" = "DESCENDING"

  @inline def values = js.Array[OrderType](ASCENDING, DESCENDING)
}

type PrincipalType = "USER" | "GROUP" | "INVITE" | "ANONYMOUS" | "ORGANIZATION"
object PrincipalType {
  val USER: "USER" = "USER"
  val GROUP: "GROUP" = "GROUP"
  val INVITE: "INVITE" = "INVITE"
  val ANONYMOUS: "ANONYMOUS" = "ANONYMOUS"
  val ORGANIZATION: "ORGANIZATION" = "ORGANIZATION"

  @inline def values = js.Array[PrincipalType](USER, GROUP, INVITE, ANONYMOUS, ORGANIZATION)
}

type ResourceCollectionType = "SHARED_WITH_ME"
object ResourceCollectionType {
  val SHARED_WITH_ME: "SHARED_WITH_ME" = "SHARED_WITH_ME"

  @inline def values = js.Array[ResourceCollectionType](SHARED_WITH_ME)
}

type ResourceSortType = "DATE" | "NAME"
object ResourceSortType {
  val DATE: "DATE" = "DATE"
  val NAME: "NAME" = "NAME"

  @inline def values = js.Array[ResourceSortType](DATE, NAME)
}

type ResourceStateType = "ACTIVE" | "RESTORING" | "RECYCLING" | "RECYCLED"
object ResourceStateType {
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val RESTORING: "RESTORING" = "RESTORING"
  val RECYCLING: "RECYCLING" = "RECYCLING"
  val RECYCLED: "RECYCLED" = "RECYCLED"

  @inline def values = js.Array[ResourceStateType](ACTIVE, RESTORING, RECYCLING, RECYCLED)
}

type ResourceType = "FOLDER" | "DOCUMENT"
object ResourceType {
  val FOLDER: "FOLDER" = "FOLDER"
  val DOCUMENT: "DOCUMENT" = "DOCUMENT"

  @inline def values = js.Array[ResourceType](FOLDER, DOCUMENT)
}

type RolePermissionType = "DIRECT" | "INHERITED"
object RolePermissionType {
  val DIRECT: "DIRECT" = "DIRECT"
  val INHERITED: "INHERITED" = "INHERITED"

  @inline def values = js.Array[RolePermissionType](DIRECT, INHERITED)
}

type RoleType = "VIEWER" | "CONTRIBUTOR" | "OWNER" | "COOWNER"
object RoleType {
  val VIEWER: "VIEWER" = "VIEWER"
  val CONTRIBUTOR: "CONTRIBUTOR" = "CONTRIBUTOR"
  val OWNER: "OWNER" = "OWNER"
  val COOWNER: "COOWNER" = "COOWNER"

  @inline def values = js.Array[RoleType](VIEWER, CONTRIBUTOR, OWNER, COOWNER)
}

type ShareStatusType = "SUCCESS" | "FAILURE"
object ShareStatusType {
  val SUCCESS: "SUCCESS" = "SUCCESS"
  val FAILURE: "FAILURE" = "FAILURE"

  @inline def values = js.Array[ShareStatusType](SUCCESS, FAILURE)
}

type StorageType = "UNLIMITED" | "QUOTA"
object StorageType {
  val UNLIMITED: "UNLIMITED" = "UNLIMITED"
  val QUOTA: "QUOTA" = "QUOTA"

  @inline def values = js.Array[StorageType](UNLIMITED, QUOTA)
}

type SubscriptionProtocolType = "HTTPS"
object SubscriptionProtocolType {
  val HTTPS: "HTTPS" = "HTTPS"

  @inline def values = js.Array[SubscriptionProtocolType](HTTPS)
}

type SubscriptionType = "ALL"
object SubscriptionType {
  val ALL: "ALL" = "ALL"

  @inline def values = js.Array[SubscriptionType](ALL)
}

type UserFilterType = "ALL" | "ACTIVE_PENDING"
object UserFilterType {
  val ALL: "ALL" = "ALL"
  val ACTIVE_PENDING: "ACTIVE_PENDING" = "ACTIVE_PENDING"

  @inline def values = js.Array[UserFilterType](ALL, ACTIVE_PENDING)
}

type UserSortType = "USER_NAME" | "FULL_NAME" | "STORAGE_LIMIT" | "USER_STATUS" | "STORAGE_USED"
object UserSortType {
  val USER_NAME: "USER_NAME" = "USER_NAME"
  val FULL_NAME: "FULL_NAME" = "FULL_NAME"
  val STORAGE_LIMIT: "STORAGE_LIMIT" = "STORAGE_LIMIT"
  val USER_STATUS: "USER_STATUS" = "USER_STATUS"
  val STORAGE_USED: "STORAGE_USED" = "STORAGE_USED"

  @inline def values = js.Array[UserSortType](USER_NAME, FULL_NAME, STORAGE_LIMIT, USER_STATUS, STORAGE_USED)
}

type UserStatusType = "ACTIVE" | "INACTIVE" | "PENDING"
object UserStatusType {
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val INACTIVE: "INACTIVE" = "INACTIVE"
  val PENDING: "PENDING" = "PENDING"

  @inline def values = js.Array[UserStatusType](ACTIVE, INACTIVE, PENDING)
}

type UserType = "USER" | "ADMIN" | "POWERUSER" | "MINIMALUSER" | "WORKSPACESUSER"
object UserType {
  val USER: "USER" = "USER"
  val ADMIN: "ADMIN" = "ADMIN"
  val POWERUSER: "POWERUSER" = "POWERUSER"
  val MINIMALUSER: "MINIMALUSER" = "MINIMALUSER"
  val WORKSPACESUSER: "WORKSPACESUSER" = "WORKSPACESUSER"

  @inline def values = js.Array[UserType](USER, ADMIN, POWERUSER, MINIMALUSER, WORKSPACESUSER)
}
