package facade.amazonaws.services.synthetics

import scalajs.js

type CanaryRunState = "RUNNING" | "PASSED" | "FAILED"
object CanaryRunState {
  inline val RUNNING: "RUNNING" = "RUNNING"
  inline val PASSED: "PASSED" = "PASSED"
  inline val FAILED: "FAILED" = "FAILED"

  inline def values: js.Array[CanaryRunState] = js.Array(RUNNING, PASSED, FAILED)
}

type CanaryRunStateReasonCode = "CANARY_FAILURE" | "EXECUTION_FAILURE"
object CanaryRunStateReasonCode {
  inline val CANARY_FAILURE: "CANARY_FAILURE" = "CANARY_FAILURE"
  inline val EXECUTION_FAILURE: "EXECUTION_FAILURE" = "EXECUTION_FAILURE"

  inline def values: js.Array[CanaryRunStateReasonCode] = js.Array(CANARY_FAILURE, EXECUTION_FAILURE)
}

type CanaryState = "CREATING" | "READY" | "STARTING" | "RUNNING" | "UPDATING" | "STOPPING" | "STOPPED" | "ERROR" | "DELETING"
object CanaryState {
  inline val CREATING: "CREATING" = "CREATING"
  inline val READY: "READY" = "READY"
  inline val STARTING: "STARTING" = "STARTING"
  inline val RUNNING: "RUNNING" = "RUNNING"
  inline val UPDATING: "UPDATING" = "UPDATING"
  inline val STOPPING: "STOPPING" = "STOPPING"
  inline val STOPPED: "STOPPED" = "STOPPED"
  inline val ERROR: "ERROR" = "ERROR"
  inline val DELETING: "DELETING" = "DELETING"

  inline def values: js.Array[CanaryState] = js.Array(CREATING, READY, STARTING, RUNNING, UPDATING, STOPPING, STOPPED, ERROR, DELETING)
}

type CanaryStateReasonCode = "INVALID_PERMISSIONS" | "CREATE_PENDING" | "CREATE_IN_PROGRESS" | "CREATE_FAILED" | "UPDATE_PENDING" | "UPDATE_IN_PROGRESS" | "UPDATE_COMPLETE" | "ROLLBACK_COMPLETE" | "ROLLBACK_FAILED" | "DELETE_IN_PROGRESS" | "DELETE_FAILED" | "SYNC_DELETE_IN_PROGRESS"
object CanaryStateReasonCode {
  inline val INVALID_PERMISSIONS: "INVALID_PERMISSIONS" = "INVALID_PERMISSIONS"
  inline val CREATE_PENDING: "CREATE_PENDING" = "CREATE_PENDING"
  inline val CREATE_IN_PROGRESS: "CREATE_IN_PROGRESS" = "CREATE_IN_PROGRESS"
  inline val CREATE_FAILED: "CREATE_FAILED" = "CREATE_FAILED"
  inline val UPDATE_PENDING: "UPDATE_PENDING" = "UPDATE_PENDING"
  inline val UPDATE_IN_PROGRESS: "UPDATE_IN_PROGRESS" = "UPDATE_IN_PROGRESS"
  inline val UPDATE_COMPLETE: "UPDATE_COMPLETE" = "UPDATE_COMPLETE"
  inline val ROLLBACK_COMPLETE: "ROLLBACK_COMPLETE" = "ROLLBACK_COMPLETE"
  inline val ROLLBACK_FAILED: "ROLLBACK_FAILED" = "ROLLBACK_FAILED"
  inline val DELETE_IN_PROGRESS: "DELETE_IN_PROGRESS" = "DELETE_IN_PROGRESS"
  inline val DELETE_FAILED: "DELETE_FAILED" = "DELETE_FAILED"
  inline val SYNC_DELETE_IN_PROGRESS: "SYNC_DELETE_IN_PROGRESS" = "SYNC_DELETE_IN_PROGRESS"

  inline def values: js.Array[CanaryStateReasonCode] = js.Array(
    INVALID_PERMISSIONS,
    CREATE_PENDING,
    CREATE_IN_PROGRESS,
    CREATE_FAILED,
    UPDATE_PENDING,
    UPDATE_IN_PROGRESS,
    UPDATE_COMPLETE,
    ROLLBACK_COMPLETE,
    ROLLBACK_FAILED,
    DELETE_IN_PROGRESS,
    DELETE_FAILED,
    SYNC_DELETE_IN_PROGRESS
  )
}

type EncryptionMode = "SSE_S3" | "SSE_KMS"
object EncryptionMode {
  inline val SSE_S3: "SSE_S3" = "SSE_S3"
  inline val SSE_KMS: "SSE_KMS" = "SSE_KMS"

  inline def values: js.Array[EncryptionMode] = js.Array(SSE_S3, SSE_KMS)
}
