package facade.amazonaws.services.appflow

import scalajs._

type AggregationType = "None" | "SingleFile"
object AggregationType {
  val None: "None" = "None"
  val SingleFile: "SingleFile" = "SingleFile"

  @inline def values = js.Array[AggregationType](None, SingleFile)
}

type AmplitudeConnectorOperator = "BETWEEN"
object AmplitudeConnectorOperator {
  val BETWEEN: "BETWEEN" = "BETWEEN"

  @inline def values = js.Array[AmplitudeConnectorOperator](BETWEEN)
}

type ConnectionMode = "Public" | "Private"
object ConnectionMode {
  val Public: "Public" = "Public"
  val Private: "Private" = "Private"

  @inline def values = js.Array[ConnectionMode](Public, Private)
}

type ConnectorType = "Salesforce" | "Singular" | "Slack" | "Redshift" | "S3" | "Marketo" | "Googleanalytics" | "Zendesk" | "Servicenow" | "Datadog" | "Trendmicro" | "Snowflake" | "Dynatrace" | "Infornexus" | "Amplitude" | "Veeva" | "EventBridge" | "LookoutMetrics" | "Upsolver" | "Honeycode" | "CustomerProfiles"
object ConnectorType {
  val Salesforce: "Salesforce" = "Salesforce"
  val Singular: "Singular" = "Singular"
  val Slack: "Slack" = "Slack"
  val Redshift: "Redshift" = "Redshift"
  val S3: "S3" = "S3"
  val Marketo: "Marketo" = "Marketo"
  val Googleanalytics: "Googleanalytics" = "Googleanalytics"
  val Zendesk: "Zendesk" = "Zendesk"
  val Servicenow: "Servicenow" = "Servicenow"
  val Datadog: "Datadog" = "Datadog"
  val Trendmicro: "Trendmicro" = "Trendmicro"
  val Snowflake: "Snowflake" = "Snowflake"
  val Dynatrace: "Dynatrace" = "Dynatrace"
  val Infornexus: "Infornexus" = "Infornexus"
  val Amplitude: "Amplitude" = "Amplitude"
  val Veeva: "Veeva" = "Veeva"
  val EventBridge: "EventBridge" = "EventBridge"
  val LookoutMetrics: "LookoutMetrics" = "LookoutMetrics"
  val Upsolver: "Upsolver" = "Upsolver"
  val Honeycode: "Honeycode" = "Honeycode"
  val CustomerProfiles: "CustomerProfiles" = "CustomerProfiles"

  @inline def values = js.Array[ConnectorType](
    Salesforce,
    Singular,
    Slack,
    Redshift,
    S3,
    Marketo,
    Googleanalytics,
    Zendesk,
    Servicenow,
    Datadog,
    Trendmicro,
    Snowflake,
    Dynatrace,
    Infornexus,
    Amplitude,
    Veeva,
    EventBridge,
    LookoutMetrics,
    Upsolver,
    Honeycode,
    CustomerProfiles
  )
}

type DataPullMode = "Incremental" | "Complete"
object DataPullMode {
  val Incremental: "Incremental" = "Incremental"
  val Complete: "Complete" = "Complete"

  @inline def values = js.Array[DataPullMode](Incremental, Complete)
}

type DatadogConnectorOperator = "PROJECTION" | "BETWEEN" | "EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object DatadogConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[DatadogConnectorOperator](
    PROJECTION,
    BETWEEN,
    EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type DynatraceConnectorOperator = "PROJECTION" | "BETWEEN" | "EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object DynatraceConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[DynatraceConnectorOperator](
    PROJECTION,
    BETWEEN,
    EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type ExecutionStatus = "InProgress" | "Successful" | "Error"
object ExecutionStatus {
  val InProgress: "InProgress" = "InProgress"
  val Successful: "Successful" = "Successful"
  val Error: "Error" = "Error"

  @inline def values = js.Array[ExecutionStatus](InProgress, Successful, Error)
}

type FileType = "CSV" | "JSON" | "PARQUET"
object FileType {
  val CSV: "CSV" = "CSV"
  val JSON: "JSON" = "JSON"
  val PARQUET: "PARQUET" = "PARQUET"

  @inline def values = js.Array[FileType](CSV, JSON, PARQUET)
}

type FlowStatus = "Active" | "Deprecated" | "Deleted" | "Draft" | "Errored" | "Suspended"
object FlowStatus {
  val Active: "Active" = "Active"
  val Deprecated: "Deprecated" = "Deprecated"
  val Deleted: "Deleted" = "Deleted"
  val Draft: "Draft" = "Draft"
  val Errored: "Errored" = "Errored"
  val Suspended: "Suspended" = "Suspended"

  @inline def values = js.Array[FlowStatus](Active, Deprecated, Deleted, Draft, Errored, Suspended)
}

type GoogleAnalyticsConnectorOperator = "PROJECTION" | "BETWEEN"
object GoogleAnalyticsConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val BETWEEN: "BETWEEN" = "BETWEEN"

  @inline def values = js.Array[GoogleAnalyticsConnectorOperator](PROJECTION, BETWEEN)
}

type InforNexusConnectorOperator = "PROJECTION" | "BETWEEN" | "EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object InforNexusConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[InforNexusConnectorOperator](
    PROJECTION,
    BETWEEN,
    EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type MarketoConnectorOperator = "PROJECTION" | "LESS_THAN" | "GREATER_THAN" | "BETWEEN" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object MarketoConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[MarketoConnectorOperator](
    PROJECTION,
    LESS_THAN,
    GREATER_THAN,
    BETWEEN,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type Operator = "PROJECTION" | "LESS_THAN" | "GREATER_THAN" | "CONTAINS" | "BETWEEN" | "LESS_THAN_OR_EQUAL_TO" | "GREATER_THAN_OR_EQUAL_TO" | "EQUAL_TO" | "NOT_EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object Operator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val CONTAINS: "CONTAINS" = "CONTAINS"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO" = "LESS_THAN_OR_EQUAL_TO"
  val GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO" = "GREATER_THAN_OR_EQUAL_TO"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val NOT_EQUAL_TO: "NOT_EQUAL_TO" = "NOT_EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[Operator](
    PROJECTION,
    LESS_THAN,
    GREATER_THAN,
    CONTAINS,
    BETWEEN,
    LESS_THAN_OR_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO,
    EQUAL_TO,
    NOT_EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type OperatorPropertiesKeys = "VALUE" | "VALUES" | "DATA_TYPE" | "UPPER_BOUND" | "LOWER_BOUND" | "SOURCE_DATA_TYPE" | "DESTINATION_DATA_TYPE" | "VALIDATION_ACTION" | "MASK_VALUE" | "MASK_LENGTH" | "TRUNCATE_LENGTH" | "MATH_OPERATION_FIELDS_ORDER" | "CONCAT_FORMAT" | "SUBFIELD_CATEGORY_MAP"
object OperatorPropertiesKeys {
  val VALUE: "VALUE" = "VALUE"
  val VALUES: "VALUES" = "VALUES"
  val DATA_TYPE: "DATA_TYPE" = "DATA_TYPE"
  val UPPER_BOUND: "UPPER_BOUND" = "UPPER_BOUND"
  val LOWER_BOUND: "LOWER_BOUND" = "LOWER_BOUND"
  val SOURCE_DATA_TYPE: "SOURCE_DATA_TYPE" = "SOURCE_DATA_TYPE"
  val DESTINATION_DATA_TYPE: "DESTINATION_DATA_TYPE" = "DESTINATION_DATA_TYPE"
  val VALIDATION_ACTION: "VALIDATION_ACTION" = "VALIDATION_ACTION"
  val MASK_VALUE: "MASK_VALUE" = "MASK_VALUE"
  val MASK_LENGTH: "MASK_LENGTH" = "MASK_LENGTH"
  val TRUNCATE_LENGTH: "TRUNCATE_LENGTH" = "TRUNCATE_LENGTH"
  val MATH_OPERATION_FIELDS_ORDER: "MATH_OPERATION_FIELDS_ORDER" = "MATH_OPERATION_FIELDS_ORDER"
  val CONCAT_FORMAT: "CONCAT_FORMAT" = "CONCAT_FORMAT"
  val SUBFIELD_CATEGORY_MAP: "SUBFIELD_CATEGORY_MAP" = "SUBFIELD_CATEGORY_MAP"

  @inline def values = js.Array[OperatorPropertiesKeys](
    VALUE,
    VALUES,
    DATA_TYPE,
    UPPER_BOUND,
    LOWER_BOUND,
    SOURCE_DATA_TYPE,
    DESTINATION_DATA_TYPE,
    VALIDATION_ACTION,
    MASK_VALUE,
    MASK_LENGTH,
    TRUNCATE_LENGTH,
    MATH_OPERATION_FIELDS_ORDER,
    CONCAT_FORMAT,
    SUBFIELD_CATEGORY_MAP
  )
}

type PrefixFormat = "YEAR" | "MONTH" | "DAY" | "HOUR" | "MINUTE"
object PrefixFormat {
  val YEAR: "YEAR" = "YEAR"
  val MONTH: "MONTH" = "MONTH"
  val DAY: "DAY" = "DAY"
  val HOUR: "HOUR" = "HOUR"
  val MINUTE: "MINUTE" = "MINUTE"

  @inline def values = js.Array[PrefixFormat](YEAR, MONTH, DAY, HOUR, MINUTE)
}

type PrefixType = "FILENAME" | "PATH" | "PATH_AND_FILENAME"
object PrefixType {
  val FILENAME: "FILENAME" = "FILENAME"
  val PATH: "PATH" = "PATH"
  val PATH_AND_FILENAME: "PATH_AND_FILENAME" = "PATH_AND_FILENAME"

  @inline def values = js.Array[PrefixType](FILENAME, PATH, PATH_AND_FILENAME)
}

type S3ConnectorOperator = "PROJECTION" | "LESS_THAN" | "GREATER_THAN" | "BETWEEN" | "LESS_THAN_OR_EQUAL_TO" | "GREATER_THAN_OR_EQUAL_TO" | "EQUAL_TO" | "NOT_EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object S3ConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO" = "LESS_THAN_OR_EQUAL_TO"
  val GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO" = "GREATER_THAN_OR_EQUAL_TO"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val NOT_EQUAL_TO: "NOT_EQUAL_TO" = "NOT_EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[S3ConnectorOperator](
    PROJECTION,
    LESS_THAN,
    GREATER_THAN,
    BETWEEN,
    LESS_THAN_OR_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO,
    EQUAL_TO,
    NOT_EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type SalesforceConnectorOperator = "PROJECTION" | "LESS_THAN" | "CONTAINS" | "GREATER_THAN" | "BETWEEN" | "LESS_THAN_OR_EQUAL_TO" | "GREATER_THAN_OR_EQUAL_TO" | "EQUAL_TO" | "NOT_EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object SalesforceConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  val CONTAINS: "CONTAINS" = "CONTAINS"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO" = "LESS_THAN_OR_EQUAL_TO"
  val GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO" = "GREATER_THAN_OR_EQUAL_TO"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val NOT_EQUAL_TO: "NOT_EQUAL_TO" = "NOT_EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[SalesforceConnectorOperator](
    PROJECTION,
    LESS_THAN,
    CONTAINS,
    GREATER_THAN,
    BETWEEN,
    LESS_THAN_OR_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO,
    EQUAL_TO,
    NOT_EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type ScheduleFrequencyType = "BYMINUTE" | "HOURLY" | "DAILY" | "WEEKLY" | "MONTHLY" | "ONCE"
object ScheduleFrequencyType {
  val BYMINUTE: "BYMINUTE" = "BYMINUTE"
  val HOURLY: "HOURLY" = "HOURLY"
  val DAILY: "DAILY" = "DAILY"
  val WEEKLY: "WEEKLY" = "WEEKLY"
  val MONTHLY: "MONTHLY" = "MONTHLY"
  val ONCE: "ONCE" = "ONCE"

  @inline def values = js.Array[ScheduleFrequencyType](BYMINUTE, HOURLY, DAILY, WEEKLY, MONTHLY, ONCE)
}

type ServiceNowConnectorOperator = "PROJECTION" | "CONTAINS" | "LESS_THAN" | "GREATER_THAN" | "BETWEEN" | "LESS_THAN_OR_EQUAL_TO" | "GREATER_THAN_OR_EQUAL_TO" | "EQUAL_TO" | "NOT_EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object ServiceNowConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val CONTAINS: "CONTAINS" = "CONTAINS"
  val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO" = "LESS_THAN_OR_EQUAL_TO"
  val GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO" = "GREATER_THAN_OR_EQUAL_TO"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val NOT_EQUAL_TO: "NOT_EQUAL_TO" = "NOT_EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[ServiceNowConnectorOperator](
    PROJECTION,
    CONTAINS,
    LESS_THAN,
    GREATER_THAN,
    BETWEEN,
    LESS_THAN_OR_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO,
    EQUAL_TO,
    NOT_EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type SingularConnectorOperator = "PROJECTION" | "EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object SingularConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[SingularConnectorOperator](
    PROJECTION,
    EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type SlackConnectorOperator = "PROJECTION" | "LESS_THAN" | "GREATER_THAN" | "BETWEEN" | "LESS_THAN_OR_EQUAL_TO" | "GREATER_THAN_OR_EQUAL_TO" | "EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object SlackConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO" = "LESS_THAN_OR_EQUAL_TO"
  val GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO" = "GREATER_THAN_OR_EQUAL_TO"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[SlackConnectorOperator](
    PROJECTION,
    LESS_THAN,
    GREATER_THAN,
    BETWEEN,
    LESS_THAN_OR_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO,
    EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type TaskType = "Arithmetic" | "Filter" | "Map" | "Mask" | "Merge" | "Truncate" | "Validate"
object TaskType {
  val Arithmetic: "Arithmetic" = "Arithmetic"
  val Filter: "Filter" = "Filter"
  val Map: "Map" = "Map"
  val Mask: "Mask" = "Mask"
  val Merge: "Merge" = "Merge"
  val Truncate: "Truncate" = "Truncate"
  val Validate: "Validate" = "Validate"

  @inline def values = js.Array[TaskType](Arithmetic, Filter, Map, Mask, Merge, Truncate, Validate)
}

type TrendmicroConnectorOperator = "PROJECTION" | "EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object TrendmicroConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[TrendmicroConnectorOperator](
    PROJECTION,
    EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

type TriggerType = "Scheduled" | "Event" | "OnDemand"
object TriggerType {
  val Scheduled: "Scheduled" = "Scheduled"
  val Event: "Event" = "Event"
  val OnDemand: "OnDemand" = "OnDemand"

  @inline def values = js.Array[TriggerType](Scheduled, Event, OnDemand)
}

type VeevaConnectorOperator = "PROJECTION" | "LESS_THAN" | "GREATER_THAN" | "CONTAINS" | "BETWEEN" | "LESS_THAN_OR_EQUAL_TO" | "GREATER_THAN_OR_EQUAL_TO" | "EQUAL_TO" | "NOT_EQUAL_TO" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object VeevaConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val LESS_THAN: "LESS_THAN" = "LESS_THAN"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val CONTAINS: "CONTAINS" = "CONTAINS"
  val BETWEEN: "BETWEEN" = "BETWEEN"
  val LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO" = "LESS_THAN_OR_EQUAL_TO"
  val GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO" = "GREATER_THAN_OR_EQUAL_TO"
  val EQUAL_TO: "EQUAL_TO" = "EQUAL_TO"
  val NOT_EQUAL_TO: "NOT_EQUAL_TO" = "NOT_EQUAL_TO"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[VeevaConnectorOperator](
    PROJECTION,
    LESS_THAN,
    GREATER_THAN,
    CONTAINS,
    BETWEEN,
    LESS_THAN_OR_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO,
    EQUAL_TO,
    NOT_EQUAL_TO,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}

/** The possible write operations in the destination connector. When this value is not provided, this defaults to the <code>INSERT</code> operation.
  */
type WriteOperationType = "INSERT" | "UPSERT" | "UPDATE"
object WriteOperationType {
  val INSERT: "INSERT" = "INSERT"
  val UPSERT: "UPSERT" = "UPSERT"
  val UPDATE: "UPDATE" = "UPDATE"

  @inline def values = js.Array[WriteOperationType](INSERT, UPSERT, UPDATE)
}

type ZendeskConnectorOperator = "PROJECTION" | "GREATER_THAN" | "ADDITION" | "MULTIPLICATION" | "DIVISION" | "SUBTRACTION" | "MASK_ALL" | "MASK_FIRST_N" | "MASK_LAST_N" | "VALIDATE_NON_NULL" | "VALIDATE_NON_ZERO" | "VALIDATE_NON_NEGATIVE" | "VALIDATE_NUMERIC" | "NO_OP"
object ZendeskConnectorOperator {
  val PROJECTION: "PROJECTION" = "PROJECTION"
  val GREATER_THAN: "GREATER_THAN" = "GREATER_THAN"
  val ADDITION: "ADDITION" = "ADDITION"
  val MULTIPLICATION: "MULTIPLICATION" = "MULTIPLICATION"
  val DIVISION: "DIVISION" = "DIVISION"
  val SUBTRACTION: "SUBTRACTION" = "SUBTRACTION"
  val MASK_ALL: "MASK_ALL" = "MASK_ALL"
  val MASK_FIRST_N: "MASK_FIRST_N" = "MASK_FIRST_N"
  val MASK_LAST_N: "MASK_LAST_N" = "MASK_LAST_N"
  val VALIDATE_NON_NULL: "VALIDATE_NON_NULL" = "VALIDATE_NON_NULL"
  val VALIDATE_NON_ZERO: "VALIDATE_NON_ZERO" = "VALIDATE_NON_ZERO"
  val VALIDATE_NON_NEGATIVE: "VALIDATE_NON_NEGATIVE" = "VALIDATE_NON_NEGATIVE"
  val VALIDATE_NUMERIC: "VALIDATE_NUMERIC" = "VALIDATE_NUMERIC"
  val NO_OP: "NO_OP" = "NO_OP"

  @inline def values = js.Array[ZendeskConnectorOperator](
    PROJECTION,
    GREATER_THAN,
    ADDITION,
    MULTIPLICATION,
    DIVISION,
    SUBTRACTION,
    MASK_ALL,
    MASK_FIRST_N,
    MASK_LAST_N,
    VALIDATE_NON_NULL,
    VALIDATE_NON_ZERO,
    VALIDATE_NON_NEGATIVE,
    VALIDATE_NUMERIC,
    NO_OP
  )
}
