package facade.amazonaws.services.lookoutvision

import scalajs._

type DatasetStatus = "CREATE_IN_PROGRESS" | "CREATE_COMPLETE" | "CREATE_FAILED" | "UPDATE_IN_PROGRESS" | "UPDATE_COMPLETE" | "UPDATE_FAILED_ROLLBACK_IN_PROGRESS" | "UPDATE_FAILED_ROLLBACK_COMPLETE" | "DELETE_IN_PROGRESS" | "DELETE_COMPLETE" | "DELETE_FAILED"
object DatasetStatus {
  val CREATE_IN_PROGRESS: "CREATE_IN_PROGRESS" = "CREATE_IN_PROGRESS"
  val CREATE_COMPLETE: "CREATE_COMPLETE" = "CREATE_COMPLETE"
  val CREATE_FAILED: "CREATE_FAILED" = "CREATE_FAILED"
  val UPDATE_IN_PROGRESS: "UPDATE_IN_PROGRESS" = "UPDATE_IN_PROGRESS"
  val UPDATE_COMPLETE: "UPDATE_COMPLETE" = "UPDATE_COMPLETE"
  val UPDATE_FAILED_ROLLBACK_IN_PROGRESS: "UPDATE_FAILED_ROLLBACK_IN_PROGRESS" = "UPDATE_FAILED_ROLLBACK_IN_PROGRESS"
  val UPDATE_FAILED_ROLLBACK_COMPLETE: "UPDATE_FAILED_ROLLBACK_COMPLETE" = "UPDATE_FAILED_ROLLBACK_COMPLETE"
  val DELETE_IN_PROGRESS: "DELETE_IN_PROGRESS" = "DELETE_IN_PROGRESS"
  val DELETE_COMPLETE: "DELETE_COMPLETE" = "DELETE_COMPLETE"
  val DELETE_FAILED: "DELETE_FAILED" = "DELETE_FAILED"

  @inline def values = js.Array[DatasetStatus](
    CREATE_IN_PROGRESS,
    CREATE_COMPLETE,
    CREATE_FAILED,
    UPDATE_IN_PROGRESS,
    UPDATE_COMPLETE,
    UPDATE_FAILED_ROLLBACK_IN_PROGRESS,
    UPDATE_FAILED_ROLLBACK_COMPLETE,
    DELETE_IN_PROGRESS,
    DELETE_COMPLETE,
    DELETE_FAILED
  )
}

type ModelHostingStatus = "STARTING_HOSTING" | "HOSTED" | "HOSTING_FAILED" | "STOPPING_HOSTING" | "SYSTEM_UPDATING"
object ModelHostingStatus {
  val STARTING_HOSTING: "STARTING_HOSTING" = "STARTING_HOSTING"
  val HOSTED: "HOSTED" = "HOSTED"
  val HOSTING_FAILED: "HOSTING_FAILED" = "HOSTING_FAILED"
  val STOPPING_HOSTING: "STOPPING_HOSTING" = "STOPPING_HOSTING"
  val SYSTEM_UPDATING: "SYSTEM_UPDATING" = "SYSTEM_UPDATING"

  @inline def values = js.Array[ModelHostingStatus](STARTING_HOSTING, HOSTED, HOSTING_FAILED, STOPPING_HOSTING, SYSTEM_UPDATING)
}

type ModelStatus = "TRAINING" | "TRAINED" | "TRAINING_FAILED" | "STARTING_HOSTING" | "HOSTED" | "HOSTING_FAILED" | "STOPPING_HOSTING" | "SYSTEM_UPDATING" | "DELETING"
object ModelStatus {
  val TRAINING: "TRAINING" = "TRAINING"
  val TRAINED: "TRAINED" = "TRAINED"
  val TRAINING_FAILED: "TRAINING_FAILED" = "TRAINING_FAILED"
  val STARTING_HOSTING: "STARTING_HOSTING" = "STARTING_HOSTING"
  val HOSTED: "HOSTED" = "HOSTED"
  val HOSTING_FAILED: "HOSTING_FAILED" = "HOSTING_FAILED"
  val STOPPING_HOSTING: "STOPPING_HOSTING" = "STOPPING_HOSTING"
  val SYSTEM_UPDATING: "SYSTEM_UPDATING" = "SYSTEM_UPDATING"
  val DELETING: "DELETING" = "DELETING"

  @inline def values = js.Array[ModelStatus](TRAINING, TRAINED, TRAINING_FAILED, STARTING_HOSTING, HOSTED, HOSTING_FAILED, STOPPING_HOSTING, SYSTEM_UPDATING, DELETING)
}
