package facade.amazonaws.services.timestreamquery

import scalajs._

type ScalarType = "VARCHAR" | "BOOLEAN" | "BIGINT" | "DOUBLE" | "TIMESTAMP" | "DATE" | "TIME" | "INTERVAL_DAY_TO_SECOND" | "INTERVAL_YEAR_TO_MONTH" | "UNKNOWN" | "INTEGER"
object ScalarType {
  val VARCHAR: "VARCHAR" = "VARCHAR"
  val BOOLEAN: "BOOLEAN" = "BOOLEAN"
  val BIGINT: "BIGINT" = "BIGINT"
  val DOUBLE: "DOUBLE" = "DOUBLE"
  val TIMESTAMP: "TIMESTAMP" = "TIMESTAMP"
  val DATE: "DATE" = "DATE"
  val TIME: "TIME" = "TIME"
  val INTERVAL_DAY_TO_SECOND: "INTERVAL_DAY_TO_SECOND" = "INTERVAL_DAY_TO_SECOND"
  val INTERVAL_YEAR_TO_MONTH: "INTERVAL_YEAR_TO_MONTH" = "INTERVAL_YEAR_TO_MONTH"
  val UNKNOWN: "UNKNOWN" = "UNKNOWN"
  val INTEGER: "INTEGER" = "INTEGER"

  @inline def values = js.Array[ScalarType](VARCHAR, BOOLEAN, BIGINT, DOUBLE, TIMESTAMP, DATE, TIME, INTERVAL_DAY_TO_SECOND, INTERVAL_YEAR_TO_MONTH, UNKNOWN, INTEGER)
}
