package facade.amazonaws.services.fms

import scalajs._

type AccountRoleStatus = "READY" | "CREATING" | "PENDING_DELETION" | "DELETING" | "DELETED"
object AccountRoleStatus {
  inline val READY: "READY" = "READY"
  inline val CREATING: "CREATING" = "CREATING"
  inline val PENDING_DELETION: "PENDING_DELETION" = "PENDING_DELETION"
  inline val DELETING: "DELETING" = "DELETING"
  inline val DELETED: "DELETED" = "DELETED"

  inline def values: js.Array[AccountRoleStatus] = js.Array(READY, CREATING, PENDING_DELETION, DELETING, DELETED)
}

type CustomerPolicyScopeIdType = "ACCOUNT" | "ORG_UNIT"
object CustomerPolicyScopeIdType {
  inline val ACCOUNT: "ACCOUNT" = "ACCOUNT"
  inline val ORG_UNIT: "ORG_UNIT" = "ORG_UNIT"

  inline def values: js.Array[CustomerPolicyScopeIdType] = js.Array(ACCOUNT, ORG_UNIT)
}

type DependentServiceName = "AWSCONFIG" | "AWSWAF" | "AWSSHIELD_ADVANCED" | "AWSVPC"
object DependentServiceName {
  inline val AWSCONFIG: "AWSCONFIG" = "AWSCONFIG"
  inline val AWSWAF: "AWSWAF" = "AWSWAF"
  inline val AWSSHIELD_ADVANCED: "AWSSHIELD_ADVANCED" = "AWSSHIELD_ADVANCED"
  inline val AWSVPC: "AWSVPC" = "AWSVPC"

  inline def values: js.Array[DependentServiceName] = js.Array(AWSCONFIG, AWSWAF, AWSSHIELD_ADVANCED, AWSVPC)
}

type PolicyComplianceStatusType = "COMPLIANT" | "NON_COMPLIANT"
object PolicyComplianceStatusType {
  inline val COMPLIANT: "COMPLIANT" = "COMPLIANT"
  inline val NON_COMPLIANT: "NON_COMPLIANT" = "NON_COMPLIANT"

  inline def values: js.Array[PolicyComplianceStatusType] = js.Array(COMPLIANT, NON_COMPLIANT)
}

type RemediationActionType = "REMOVE" | "MODIFY"
object RemediationActionType {
  inline val REMOVE: "REMOVE" = "REMOVE"
  inline val MODIFY: "MODIFY" = "MODIFY"

  inline def values: js.Array[RemediationActionType] = js.Array(REMOVE, MODIFY)
}

type SecurityServiceType = "WAF" | "WAFV2" | "SHIELD_ADVANCED" | "SECURITY_GROUPS_COMMON" | "SECURITY_GROUPS_CONTENT_AUDIT" | "SECURITY_GROUPS_USAGE_AUDIT" | "NETWORK_FIREWALL" | "DNS_FIREWALL"
object SecurityServiceType {
  inline val WAF: "WAF" = "WAF"
  inline val WAFV2: "WAFV2" = "WAFV2"
  inline val SHIELD_ADVANCED: "SHIELD_ADVANCED" = "SHIELD_ADVANCED"
  inline val SECURITY_GROUPS_COMMON: "SECURITY_GROUPS_COMMON" = "SECURITY_GROUPS_COMMON"
  inline val SECURITY_GROUPS_CONTENT_AUDIT: "SECURITY_GROUPS_CONTENT_AUDIT" = "SECURITY_GROUPS_CONTENT_AUDIT"
  inline val SECURITY_GROUPS_USAGE_AUDIT: "SECURITY_GROUPS_USAGE_AUDIT" = "SECURITY_GROUPS_USAGE_AUDIT"
  inline val NETWORK_FIREWALL: "NETWORK_FIREWALL" = "NETWORK_FIREWALL"
  inline val DNS_FIREWALL: "DNS_FIREWALL" = "DNS_FIREWALL"

  inline def values: js.Array[SecurityServiceType] = js.Array(WAF, WAFV2, SHIELD_ADVANCED, SECURITY_GROUPS_COMMON, SECURITY_GROUPS_CONTENT_AUDIT, SECURITY_GROUPS_USAGE_AUDIT, NETWORK_FIREWALL, DNS_FIREWALL)
}

type ViolationReason = "WEB_ACL_MISSING_RULE_GROUP" | "RESOURCE_MISSING_WEB_ACL" | "RESOURCE_INCORRECT_WEB_ACL" | "RESOURCE_MISSING_SHIELD_PROTECTION" | "RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION" | "RESOURCE_MISSING_SECURITY_GROUP" | "RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP" | "SECURITY_GROUP_UNUSED" | "SECURITY_GROUP_REDUNDANT" | "FMS_CREATED_SECURITY_GROUP_EDITED" | "MISSING_FIREWALL" | "MISSING_FIREWALL_SUBNET_IN_AZ" | "MISSING_EXPECTED_ROUTE_TABLE" | "NETWORK_FIREWALL_POLICY_MODIFIED" | "RESOURCE_MISSING_DNS_FIREWALL"
object ViolationReason {
  inline val WEB_ACL_MISSING_RULE_GROUP: "WEB_ACL_MISSING_RULE_GROUP" = "WEB_ACL_MISSING_RULE_GROUP"
  inline val RESOURCE_MISSING_WEB_ACL: "RESOURCE_MISSING_WEB_ACL" = "RESOURCE_MISSING_WEB_ACL"
  inline val RESOURCE_INCORRECT_WEB_ACL: "RESOURCE_INCORRECT_WEB_ACL" = "RESOURCE_INCORRECT_WEB_ACL"
  inline val RESOURCE_MISSING_SHIELD_PROTECTION: "RESOURCE_MISSING_SHIELD_PROTECTION" = "RESOURCE_MISSING_SHIELD_PROTECTION"
  inline val RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION: "RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION" = "RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION"
  inline val RESOURCE_MISSING_SECURITY_GROUP: "RESOURCE_MISSING_SECURITY_GROUP" = "RESOURCE_MISSING_SECURITY_GROUP"
  inline val RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP: "RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP" = "RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP"
  inline val SECURITY_GROUP_UNUSED: "SECURITY_GROUP_UNUSED" = "SECURITY_GROUP_UNUSED"
  inline val SECURITY_GROUP_REDUNDANT: "SECURITY_GROUP_REDUNDANT" = "SECURITY_GROUP_REDUNDANT"
  inline val FMS_CREATED_SECURITY_GROUP_EDITED: "FMS_CREATED_SECURITY_GROUP_EDITED" = "FMS_CREATED_SECURITY_GROUP_EDITED"
  inline val MISSING_FIREWALL: "MISSING_FIREWALL" = "MISSING_FIREWALL"
  inline val MISSING_FIREWALL_SUBNET_IN_AZ: "MISSING_FIREWALL_SUBNET_IN_AZ" = "MISSING_FIREWALL_SUBNET_IN_AZ"
  inline val MISSING_EXPECTED_ROUTE_TABLE: "MISSING_EXPECTED_ROUTE_TABLE" = "MISSING_EXPECTED_ROUTE_TABLE"
  inline val NETWORK_FIREWALL_POLICY_MODIFIED: "NETWORK_FIREWALL_POLICY_MODIFIED" = "NETWORK_FIREWALL_POLICY_MODIFIED"
  inline val RESOURCE_MISSING_DNS_FIREWALL: "RESOURCE_MISSING_DNS_FIREWALL" = "RESOURCE_MISSING_DNS_FIREWALL"

  inline def values: js.Array[ViolationReason] = js.Array(
    WEB_ACL_MISSING_RULE_GROUP,
    RESOURCE_MISSING_WEB_ACL,
    RESOURCE_INCORRECT_WEB_ACL,
    RESOURCE_MISSING_SHIELD_PROTECTION,
    RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION,
    RESOURCE_MISSING_SECURITY_GROUP,
    RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP,
    SECURITY_GROUP_UNUSED,
    SECURITY_GROUP_REDUNDANT,
    FMS_CREATED_SECURITY_GROUP_EDITED,
    MISSING_FIREWALL,
    MISSING_FIREWALL_SUBNET_IN_AZ,
    MISSING_EXPECTED_ROUTE_TABLE,
    NETWORK_FIREWALL_POLICY_MODIFIED,
    RESOURCE_MISSING_DNS_FIREWALL
  )
}
