package facade.amazonaws.services.fms

import scalajs._

type AccountRoleStatus = "READY" | "CREATING" | "PENDING_DELETION" | "DELETING" | "DELETED"
object AccountRoleStatus {
  val READY: "READY" = "READY"
  val CREATING: "CREATING" = "CREATING"
  val PENDING_DELETION: "PENDING_DELETION" = "PENDING_DELETION"
  val DELETING: "DELETING" = "DELETING"
  val DELETED: "DELETED" = "DELETED"

  @inline def values = js.Array[AccountRoleStatus](READY, CREATING, PENDING_DELETION, DELETING, DELETED)
}

type CustomerPolicyScopeIdType = "ACCOUNT" | "ORG_UNIT"
object CustomerPolicyScopeIdType {
  val ACCOUNT: "ACCOUNT" = "ACCOUNT"
  val ORG_UNIT: "ORG_UNIT" = "ORG_UNIT"

  @inline def values = js.Array[CustomerPolicyScopeIdType](ACCOUNT, ORG_UNIT)
}

type DependentServiceName = "AWSCONFIG" | "AWSWAF" | "AWSSHIELD_ADVANCED" | "AWSVPC"
object DependentServiceName {
  val AWSCONFIG: "AWSCONFIG" = "AWSCONFIG"
  val AWSWAF: "AWSWAF" = "AWSWAF"
  val AWSSHIELD_ADVANCED: "AWSSHIELD_ADVANCED" = "AWSSHIELD_ADVANCED"
  val AWSVPC: "AWSVPC" = "AWSVPC"

  @inline def values = js.Array[DependentServiceName](AWSCONFIG, AWSWAF, AWSSHIELD_ADVANCED, AWSVPC)
}

type PolicyComplianceStatusType = "COMPLIANT" | "NON_COMPLIANT"
object PolicyComplianceStatusType {
  val COMPLIANT: "COMPLIANT" = "COMPLIANT"
  val NON_COMPLIANT: "NON_COMPLIANT" = "NON_COMPLIANT"

  @inline def values = js.Array[PolicyComplianceStatusType](COMPLIANT, NON_COMPLIANT)
}

type RemediationActionType = "REMOVE" | "MODIFY"
object RemediationActionType {
  val REMOVE: "REMOVE" = "REMOVE"
  val MODIFY: "MODIFY" = "MODIFY"

  @inline def values = js.Array[RemediationActionType](REMOVE, MODIFY)
}

type SecurityServiceType = "WAF" | "WAFV2" | "SHIELD_ADVANCED" | "SECURITY_GROUPS_COMMON" | "SECURITY_GROUPS_CONTENT_AUDIT" | "SECURITY_GROUPS_USAGE_AUDIT" | "NETWORK_FIREWALL" | "DNS_FIREWALL"
object SecurityServiceType {
  val WAF: "WAF" = "WAF"
  val WAFV2: "WAFV2" = "WAFV2"
  val SHIELD_ADVANCED: "SHIELD_ADVANCED" = "SHIELD_ADVANCED"
  val SECURITY_GROUPS_COMMON: "SECURITY_GROUPS_COMMON" = "SECURITY_GROUPS_COMMON"
  val SECURITY_GROUPS_CONTENT_AUDIT: "SECURITY_GROUPS_CONTENT_AUDIT" = "SECURITY_GROUPS_CONTENT_AUDIT"
  val SECURITY_GROUPS_USAGE_AUDIT: "SECURITY_GROUPS_USAGE_AUDIT" = "SECURITY_GROUPS_USAGE_AUDIT"
  val NETWORK_FIREWALL: "NETWORK_FIREWALL" = "NETWORK_FIREWALL"
  val DNS_FIREWALL: "DNS_FIREWALL" = "DNS_FIREWALL"

  @inline def values = js.Array[SecurityServiceType](WAF, WAFV2, SHIELD_ADVANCED, SECURITY_GROUPS_COMMON, SECURITY_GROUPS_CONTENT_AUDIT, SECURITY_GROUPS_USAGE_AUDIT, NETWORK_FIREWALL, DNS_FIREWALL)
}

type ViolationReason = "WEB_ACL_MISSING_RULE_GROUP" | "RESOURCE_MISSING_WEB_ACL" | "RESOURCE_INCORRECT_WEB_ACL" | "RESOURCE_MISSING_SHIELD_PROTECTION" | "RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION" | "RESOURCE_MISSING_SECURITY_GROUP" | "RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP" | "SECURITY_GROUP_UNUSED" | "SECURITY_GROUP_REDUNDANT" | "FMS_CREATED_SECURITY_GROUP_EDITED" | "MISSING_FIREWALL" | "MISSING_FIREWALL_SUBNET_IN_AZ" | "MISSING_EXPECTED_ROUTE_TABLE" | "NETWORK_FIREWALL_POLICY_MODIFIED" | "RESOURCE_MISSING_DNS_FIREWALL"
object ViolationReason {
  val WEB_ACL_MISSING_RULE_GROUP: "WEB_ACL_MISSING_RULE_GROUP" = "WEB_ACL_MISSING_RULE_GROUP"
  val RESOURCE_MISSING_WEB_ACL: "RESOURCE_MISSING_WEB_ACL" = "RESOURCE_MISSING_WEB_ACL"
  val RESOURCE_INCORRECT_WEB_ACL: "RESOURCE_INCORRECT_WEB_ACL" = "RESOURCE_INCORRECT_WEB_ACL"
  val RESOURCE_MISSING_SHIELD_PROTECTION: "RESOURCE_MISSING_SHIELD_PROTECTION" = "RESOURCE_MISSING_SHIELD_PROTECTION"
  val RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION: "RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION" = "RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION"
  val RESOURCE_MISSING_SECURITY_GROUP: "RESOURCE_MISSING_SECURITY_GROUP" = "RESOURCE_MISSING_SECURITY_GROUP"
  val RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP: "RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP" = "RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP"
  val SECURITY_GROUP_UNUSED: "SECURITY_GROUP_UNUSED" = "SECURITY_GROUP_UNUSED"
  val SECURITY_GROUP_REDUNDANT: "SECURITY_GROUP_REDUNDANT" = "SECURITY_GROUP_REDUNDANT"
  val FMS_CREATED_SECURITY_GROUP_EDITED: "FMS_CREATED_SECURITY_GROUP_EDITED" = "FMS_CREATED_SECURITY_GROUP_EDITED"
  val MISSING_FIREWALL: "MISSING_FIREWALL" = "MISSING_FIREWALL"
  val MISSING_FIREWALL_SUBNET_IN_AZ: "MISSING_FIREWALL_SUBNET_IN_AZ" = "MISSING_FIREWALL_SUBNET_IN_AZ"
  val MISSING_EXPECTED_ROUTE_TABLE: "MISSING_EXPECTED_ROUTE_TABLE" = "MISSING_EXPECTED_ROUTE_TABLE"
  val NETWORK_FIREWALL_POLICY_MODIFIED: "NETWORK_FIREWALL_POLICY_MODIFIED" = "NETWORK_FIREWALL_POLICY_MODIFIED"
  val RESOURCE_MISSING_DNS_FIREWALL: "RESOURCE_MISSING_DNS_FIREWALL" = "RESOURCE_MISSING_DNS_FIREWALL"

  @inline def values = js.Array[ViolationReason](
    WEB_ACL_MISSING_RULE_GROUP,
    RESOURCE_MISSING_WEB_ACL,
    RESOURCE_INCORRECT_WEB_ACL,
    RESOURCE_MISSING_SHIELD_PROTECTION,
    RESOURCE_MISSING_WEB_ACL_OR_SHIELD_PROTECTION,
    RESOURCE_MISSING_SECURITY_GROUP,
    RESOURCE_VIOLATES_AUDIT_SECURITY_GROUP,
    SECURITY_GROUP_UNUSED,
    SECURITY_GROUP_REDUNDANT,
    FMS_CREATED_SECURITY_GROUP_EDITED,
    MISSING_FIREWALL,
    MISSING_FIREWALL_SUBNET_IN_AZ,
    MISSING_EXPECTED_ROUTE_TABLE,
    NETWORK_FIREWALL_POLICY_MODIFIED,
    RESOURCE_MISSING_DNS_FIREWALL
  )
}
