package facade.amazonaws.services.sms

import scalajs._

type AppLaunchConfigurationStatus = "NOT_CONFIGURED" | "CONFIGURED"
object AppLaunchConfigurationStatus {
  val NOT_CONFIGURED: "NOT_CONFIGURED" = "NOT_CONFIGURED"
  val CONFIGURED: "CONFIGURED" = "CONFIGURED"

  @inline def values = js.Array[AppLaunchConfigurationStatus](NOT_CONFIGURED, CONFIGURED)
}

type AppLaunchStatus = "READY_FOR_CONFIGURATION" | "CONFIGURATION_IN_PROGRESS" | "CONFIGURATION_INVALID" | "READY_FOR_LAUNCH" | "VALIDATION_IN_PROGRESS" | "LAUNCH_PENDING" | "LAUNCH_IN_PROGRESS" | "LAUNCHED" | "PARTIALLY_LAUNCHED" | "DELTA_LAUNCH_IN_PROGRESS" | "DELTA_LAUNCH_FAILED" | "LAUNCH_FAILED" | "TERMINATE_IN_PROGRESS" | "TERMINATE_FAILED" | "TERMINATED"
object AppLaunchStatus {
  val READY_FOR_CONFIGURATION: "READY_FOR_CONFIGURATION" = "READY_FOR_CONFIGURATION"
  val CONFIGURATION_IN_PROGRESS: "CONFIGURATION_IN_PROGRESS" = "CONFIGURATION_IN_PROGRESS"
  val CONFIGURATION_INVALID: "CONFIGURATION_INVALID" = "CONFIGURATION_INVALID"
  val READY_FOR_LAUNCH: "READY_FOR_LAUNCH" = "READY_FOR_LAUNCH"
  val VALIDATION_IN_PROGRESS: "VALIDATION_IN_PROGRESS" = "VALIDATION_IN_PROGRESS"
  val LAUNCH_PENDING: "LAUNCH_PENDING" = "LAUNCH_PENDING"
  val LAUNCH_IN_PROGRESS: "LAUNCH_IN_PROGRESS" = "LAUNCH_IN_PROGRESS"
  val LAUNCHED: "LAUNCHED" = "LAUNCHED"
  val PARTIALLY_LAUNCHED: "PARTIALLY_LAUNCHED" = "PARTIALLY_LAUNCHED"
  val DELTA_LAUNCH_IN_PROGRESS: "DELTA_LAUNCH_IN_PROGRESS" = "DELTA_LAUNCH_IN_PROGRESS"
  val DELTA_LAUNCH_FAILED: "DELTA_LAUNCH_FAILED" = "DELTA_LAUNCH_FAILED"
  val LAUNCH_FAILED: "LAUNCH_FAILED" = "LAUNCH_FAILED"
  val TERMINATE_IN_PROGRESS: "TERMINATE_IN_PROGRESS" = "TERMINATE_IN_PROGRESS"
  val TERMINATE_FAILED: "TERMINATE_FAILED" = "TERMINATE_FAILED"
  val TERMINATED: "TERMINATED" = "TERMINATED"

  @inline def values = js.Array[AppLaunchStatus](
    READY_FOR_CONFIGURATION,
    CONFIGURATION_IN_PROGRESS,
    CONFIGURATION_INVALID,
    READY_FOR_LAUNCH,
    VALIDATION_IN_PROGRESS,
    LAUNCH_PENDING,
    LAUNCH_IN_PROGRESS,
    LAUNCHED,
    PARTIALLY_LAUNCHED,
    DELTA_LAUNCH_IN_PROGRESS,
    DELTA_LAUNCH_FAILED,
    LAUNCH_FAILED,
    TERMINATE_IN_PROGRESS,
    TERMINATE_FAILED,
    TERMINATED
  )
}

type AppReplicationConfigurationStatus = "NOT_CONFIGURED" | "CONFIGURED"
object AppReplicationConfigurationStatus {
  val NOT_CONFIGURED: "NOT_CONFIGURED" = "NOT_CONFIGURED"
  val CONFIGURED: "CONFIGURED" = "CONFIGURED"

  @inline def values = js.Array[AppReplicationConfigurationStatus](NOT_CONFIGURED, CONFIGURED)
}

type AppReplicationStatus = "READY_FOR_CONFIGURATION" | "CONFIGURATION_IN_PROGRESS" | "CONFIGURATION_INVALID" | "READY_FOR_REPLICATION" | "VALIDATION_IN_PROGRESS" | "REPLICATION_PENDING" | "REPLICATION_IN_PROGRESS" | "REPLICATED" | "PARTIALLY_REPLICATED" | "DELTA_REPLICATION_IN_PROGRESS" | "DELTA_REPLICATED" | "DELTA_REPLICATION_FAILED" | "REPLICATION_FAILED" | "REPLICATION_STOPPING" | "REPLICATION_STOP_FAILED" | "REPLICATION_STOPPED"
object AppReplicationStatus {
  val READY_FOR_CONFIGURATION: "READY_FOR_CONFIGURATION" = "READY_FOR_CONFIGURATION"
  val CONFIGURATION_IN_PROGRESS: "CONFIGURATION_IN_PROGRESS" = "CONFIGURATION_IN_PROGRESS"
  val CONFIGURATION_INVALID: "CONFIGURATION_INVALID" = "CONFIGURATION_INVALID"
  val READY_FOR_REPLICATION: "READY_FOR_REPLICATION" = "READY_FOR_REPLICATION"
  val VALIDATION_IN_PROGRESS: "VALIDATION_IN_PROGRESS" = "VALIDATION_IN_PROGRESS"
  val REPLICATION_PENDING: "REPLICATION_PENDING" = "REPLICATION_PENDING"
  val REPLICATION_IN_PROGRESS: "REPLICATION_IN_PROGRESS" = "REPLICATION_IN_PROGRESS"
  val REPLICATED: "REPLICATED" = "REPLICATED"
  val PARTIALLY_REPLICATED: "PARTIALLY_REPLICATED" = "PARTIALLY_REPLICATED"
  val DELTA_REPLICATION_IN_PROGRESS: "DELTA_REPLICATION_IN_PROGRESS" = "DELTA_REPLICATION_IN_PROGRESS"
  val DELTA_REPLICATED: "DELTA_REPLICATED" = "DELTA_REPLICATED"
  val DELTA_REPLICATION_FAILED: "DELTA_REPLICATION_FAILED" = "DELTA_REPLICATION_FAILED"
  val REPLICATION_FAILED: "REPLICATION_FAILED" = "REPLICATION_FAILED"
  val REPLICATION_STOPPING: "REPLICATION_STOPPING" = "REPLICATION_STOPPING"
  val REPLICATION_STOP_FAILED: "REPLICATION_STOP_FAILED" = "REPLICATION_STOP_FAILED"
  val REPLICATION_STOPPED: "REPLICATION_STOPPED" = "REPLICATION_STOPPED"

  @inline def values = js.Array[AppReplicationStatus](
    READY_FOR_CONFIGURATION,
    CONFIGURATION_IN_PROGRESS,
    CONFIGURATION_INVALID,
    READY_FOR_REPLICATION,
    VALIDATION_IN_PROGRESS,
    REPLICATION_PENDING,
    REPLICATION_IN_PROGRESS,
    REPLICATED,
    PARTIALLY_REPLICATED,
    DELTA_REPLICATION_IN_PROGRESS,
    DELTA_REPLICATED,
    DELTA_REPLICATION_FAILED,
    REPLICATION_FAILED,
    REPLICATION_STOPPING,
    REPLICATION_STOP_FAILED,
    REPLICATION_STOPPED
  )
}

type AppStatus = "CREATING" | "ACTIVE" | "UPDATING" | "DELETING" | "DELETED" | "DELETE_FAILED"
object AppStatus {
  val CREATING: "CREATING" = "CREATING"
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val UPDATING: "UPDATING" = "UPDATING"
  val DELETING: "DELETING" = "DELETING"
  val DELETED: "DELETED" = "DELETED"
  val DELETE_FAILED: "DELETE_FAILED" = "DELETE_FAILED"

  @inline def values = js.Array[AppStatus](CREATING, ACTIVE, UPDATING, DELETING, DELETED, DELETE_FAILED)
}

type AppValidationStrategy = "SSM"
object AppValidationStrategy {
  val SSM: "SSM" = "SSM"

  @inline def values = js.Array[AppValidationStrategy](SSM)
}

type ConnectorCapability = "VSPHERE" | "SCVMM" | "HYPERV-MANAGER" | "SNAPSHOT_BATCHING" | "SMS_OPTIMIZED"
object ConnectorCapability {
  val VSPHERE: "VSPHERE" = "VSPHERE"
  val SCVMM: "SCVMM" = "SCVMM"
  val `HYPERV-MANAGER`: "HYPERV-MANAGER" = "HYPERV-MANAGER"
  val SNAPSHOT_BATCHING: "SNAPSHOT_BATCHING" = "SNAPSHOT_BATCHING"
  val SMS_OPTIMIZED: "SMS_OPTIMIZED" = "SMS_OPTIMIZED"

  @inline def values = js.Array[ConnectorCapability](VSPHERE, SCVMM, `HYPERV-MANAGER`, SNAPSHOT_BATCHING, SMS_OPTIMIZED)
}

type ConnectorStatus = "HEALTHY" | "UNHEALTHY"
object ConnectorStatus {
  val HEALTHY: "HEALTHY" = "HEALTHY"
  val UNHEALTHY: "UNHEALTHY" = "UNHEALTHY"

  @inline def values = js.Array[ConnectorStatus](HEALTHY, UNHEALTHY)
}

type LicenseType = "AWS" | "BYOL"
object LicenseType {
  val AWS: "AWS" = "AWS"
  val BYOL: "BYOL" = "BYOL"

  @inline def values = js.Array[LicenseType](AWS, BYOL)
}

type OutputFormat = "JSON" | "YAML"
object OutputFormat {
  val JSON: "JSON" = "JSON"
  val YAML: "YAML" = "YAML"

  @inline def values = js.Array[OutputFormat](JSON, YAML)
}

type ReplicationJobState = "PENDING" | "ACTIVE" | "FAILED" | "DELETING" | "DELETED" | "COMPLETED" | "PAUSED_ON_FAILURE" | "FAILING"
object ReplicationJobState {
  val PENDING: "PENDING" = "PENDING"
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val FAILED: "FAILED" = "FAILED"
  val DELETING: "DELETING" = "DELETING"
  val DELETED: "DELETED" = "DELETED"
  val COMPLETED: "COMPLETED" = "COMPLETED"
  val PAUSED_ON_FAILURE: "PAUSED_ON_FAILURE" = "PAUSED_ON_FAILURE"
  val FAILING: "FAILING" = "FAILING"

  @inline def values = js.Array[ReplicationJobState](PENDING, ACTIVE, FAILED, DELETING, DELETED, COMPLETED, PAUSED_ON_FAILURE, FAILING)
}

type ReplicationRunState = "PENDING" | "MISSED" | "ACTIVE" | "FAILED" | "COMPLETED" | "DELETING" | "DELETED"
object ReplicationRunState {
  val PENDING: "PENDING" = "PENDING"
  val MISSED: "MISSED" = "MISSED"
  val ACTIVE: "ACTIVE" = "ACTIVE"
  val FAILED: "FAILED" = "FAILED"
  val COMPLETED: "COMPLETED" = "COMPLETED"
  val DELETING: "DELETING" = "DELETING"
  val DELETED: "DELETED" = "DELETED"

  @inline def values = js.Array[ReplicationRunState](PENDING, MISSED, ACTIVE, FAILED, COMPLETED, DELETING, DELETED)
}

type ReplicationRunType = "ON_DEMAND" | "AUTOMATIC"
object ReplicationRunType {
  val ON_DEMAND: "ON_DEMAND" = "ON_DEMAND"
  val AUTOMATIC: "AUTOMATIC" = "AUTOMATIC"

  @inline def values = js.Array[ReplicationRunType](ON_DEMAND, AUTOMATIC)
}

type ScriptType = "SHELL_SCRIPT" | "POWERSHELL_SCRIPT"
object ScriptType {
  val SHELL_SCRIPT: "SHELL_SCRIPT" = "SHELL_SCRIPT"
  val POWERSHELL_SCRIPT: "POWERSHELL_SCRIPT" = "POWERSHELL_SCRIPT"

  @inline def values = js.Array[ScriptType](SHELL_SCRIPT, POWERSHELL_SCRIPT)
}

type ServerCatalogStatus = "NOT_IMPORTED" | "IMPORTING" | "AVAILABLE" | "DELETED" | "EXPIRED"
object ServerCatalogStatus {
  val NOT_IMPORTED: "NOT_IMPORTED" = "NOT_IMPORTED"
  val IMPORTING: "IMPORTING" = "IMPORTING"
  val AVAILABLE: "AVAILABLE" = "AVAILABLE"
  val DELETED: "DELETED" = "DELETED"
  val EXPIRED: "EXPIRED" = "EXPIRED"

  @inline def values = js.Array[ServerCatalogStatus](NOT_IMPORTED, IMPORTING, AVAILABLE, DELETED, EXPIRED)
}

type ServerType = "VIRTUAL_MACHINE"
object ServerType {
  val VIRTUAL_MACHINE: "VIRTUAL_MACHINE" = "VIRTUAL_MACHINE"

  @inline def values = js.Array[ServerType](VIRTUAL_MACHINE)
}

type ServerValidationStrategy = "USERDATA"
object ServerValidationStrategy {
  val USERDATA: "USERDATA" = "USERDATA"

  @inline def values = js.Array[ServerValidationStrategy](USERDATA)
}

type ValidationStatus = "READY_FOR_VALIDATION" | "PENDING" | "IN_PROGRESS" | "SUCCEEDED" | "FAILED"
object ValidationStatus {
  val READY_FOR_VALIDATION: "READY_FOR_VALIDATION" = "READY_FOR_VALIDATION"
  val PENDING: "PENDING" = "PENDING"
  val IN_PROGRESS: "IN_PROGRESS" = "IN_PROGRESS"
  val SUCCEEDED: "SUCCEEDED" = "SUCCEEDED"
  val FAILED: "FAILED" = "FAILED"

  @inline def values = js.Array[ValidationStatus](READY_FOR_VALIDATION, PENDING, IN_PROGRESS, SUCCEEDED, FAILED)
}

type VmManagerType = "VSPHERE" | "SCVMM" | "HYPERV-MANAGER"
object VmManagerType {
  val VSPHERE: "VSPHERE" = "VSPHERE"
  val SCVMM: "SCVMM" = "SCVMM"
  val `HYPERV-MANAGER`: "HYPERV-MANAGER" = "HYPERV-MANAGER"

  @inline def values = js.Array[VmManagerType](VSPHERE, SCVMM, `HYPERV-MANAGER`)
}
