name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [3.1.0, 2.13.7, 2.12.15]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Cache Coursier
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-${{ hashFiles('project/*.sbt', 'project/*.scala') }}
      - name: Cache SBT
        uses: actions/cache@v2.1.7
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('project/build.properties', 'project/plugins.sbt') }}
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'
      - run: npm install
      - name: Run Tests
        env:
          JAVA_OPTS: -Xss4M -Xms2G -Xmx8G -XX:ReservedCodeCacheSize=512M -XX:MaxMetaspaceSize=8G -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC
          JVM_OPTS: -Xss4M -Xms2G -Xmx8G -XX:ReservedCodeCacheSize=512M -XX:MaxMetaspaceSize=8G -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC
        run: sbt ++${{ matrix.scala }} core/test awsDynamoDB/test awsS3/test awsCloudFrontSigner/test credentials/test all/test
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install Scalafmt Native
        shell: bash
        run: |
          SCALAFMT_VERSION=$(grep "version" .scalafmt.conf | sed -E "s/version|=|\"|\s*//g")
          curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | sudo bash -s -- ${SCALAFMT_VERSION}
      - name: Quick check
        if: ${{ ! contains(steps.changed-files.outputs.all_modified_files, '.scalafmt.conf') }}
        run: scalafmt-native --mode diff --list
      - name: Full check
        if: ${{ contains(steps.changed-files.outputs.all_modified_files, '.scalafmt.conf') }}
        run: scalafmt-native --check
