name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.5, 2.12.13]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Cache Coursier
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-${{ hashFiles('project/*.sbt', 'project/*.scala') }}
      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('project/build.properties', 'project/plugins.sbt') }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: npm install
      - name: Run Tests
        run: sbt -jvm-opts .github/.jvmopts ++${{ matrix.scala }} core/test awsDynamoDB/test awsS3/test awsCloudFrontSigner/test all/test
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
      - name: Cache Coursier
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-${{ hashFiles('project/*.sbt', 'project/*.scala') }}
      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('project/build.properties', 'project/plugins.sbt') }}
      - name: Check Scalafmt
        run: sbt -jvm-opts .github/.jvmopts scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
