name: CI
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-${{ hashFiles('project/*.sbt', 'project/*.scala') }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('project/build.properties', 'project/plugins.sbt') }}
      - name: Check Scalafmt
        run: sbt -jvm-opts .github/.jvmopts ++2.13.5 scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
