name: CI
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Check Scalafmt
        run: sbt -jvm-opts .github/.jvmopts ++2.13.4 scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
