name: CI
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Check Scalafmt
        run: sbt -jvm-opts .travis/jvmopts ++2.13.1 scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
